### ISSUE TITLE
Trace external requests to geonames

### ISSUE THREAD

**Issue by jechols** [OregonDigital/OD2#1020]
### Descriptive summary

This would be useful if we find we continue to hit limits for geonames on staging before we start going down the path of a paid geonames account, unless we believe we're actually hitting limits for a good reason (i.e., we're actually needing all the labels we fetch, we definitely aren't pulling stuff that's already been cached, and we're confident there are no extraneous requests happening somewhere in the stack).

Basically we set up a MITM proxy, something like https://github.com/elazarl/goproxy.  We use that to log all traffic that's getting sent out from the stack, at least in terms of which URLs are being requested.

It's been suggested that we could just watch the Rails traffic pretty easily with honeycomb, but (a) it's not all that easy to do (not everything is actually using Faraday, so we'd have to hook lower-level TCP primitives), and (b) everything that requests labels *should* be going through Blazegraph, not hitting the endpoints directly.

### Expected behavior

More data to help inform decision-making.  We may or may not get anything actionable, however.

### Related work

#991

**Comment by straleyb** [comment]
Geonames gets hits each time a parent is requested through the recursive parent search for geonames. This can be anywhere between 5 and 10 requests per hit. This is due to trying to grab broader information to have labels be much more useful than just a location name. 

This also runs our limit up pretty fast. If 1000 works are being ingested and for each work that is a location that is hitting geonames 10 times. That means geonames would be hit a total of 10,000 times. Which would blow the limit out of the water. At least hourly. If we could stagger those hits however, then we could work on preloading the cache slowly so we dont hit the limit.

**Comment by wickr** [comment]
Don't think we need a separate proxy or anything to track this, other focus will be in #991.
