### ISSUE TITLE
Date Uploaded indexing should accept EDTF and mm/dd/yyyy

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1097]
### Descriptive summary
Uploaded dates (:date_uploaded) from OD1 migrated data is coming in as mm/dd/yyyy. OD2 data is being stored as EDTF. Both of which is stored in Fedora.

While indexing works with differing date formats in Fedora into Solr, date_uploaded is getting confused and sometimes erroring out. Ruby's `String.to_time` is parsing the EDTF fine, but transposing mm/dd/yyyy with dd/mm/yyyy. This is either a locale issue or just innate to ruby.

The solution, for now until a ticket is opened in the migrator (to come), is to check the date format ahead of parsing in the indexer.
Some very janky psuedocode:
```
if date.format is EDTF:
  index date_uploaded_dtsi as date.to_time
else
  index date_uploaded_dtsi as date.parse_as(mm/dd/yy)
```

### Expected behavior
Indexing date_uploaded with value `10/28/2014` doesn't throw an exception
Indexing date_uploaded with value `06/10/2014` doesn't index as `2014-10-06...` but `2014-06-10...`

### Related work
https://github.com/OregonDigital/OD2/blob/master/app/indexers/generic_indexer.rb#L25

### Accessibility Concerns
N/A

**Comment by luisgreg99** [comment]
QA Pass:

I gave it a pass since it didn't throw errors when attempting to re-index `fx719q99q` and `fx719q37q` over the console:
- `fx719q99q` has `date_uploaded` set to `"2014-10-30"`
- `fx719q37q` has `date_uploaded` set to `"10/28/2014"`

It looks like https://github.com/OregonDigital/OD2/pull/1098 skips `date_uploaded` to prevent errors for now. 

I'll move this one to done, and work on the migrator side to address https://github.com/OregonDigital/hyrax-migrator/issues/194. I'll push an update to return the expected DateTime object as pointed out in the comment https://github.com/OregonDigital/hyrax-migrator/issues/194#issuecomment-608591654
