### ISSUE TITLE
Work surrounding OCR

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#1110]
### Descriptive summary

OCR is going to be a larger chunk of work that could use some discussion. 

@decimalator @jechols Im linking you two because we'll need to install some lower level libraries and it may be worth while to discuss how we want to do that. Tesseract is a low level library that would need to be compiled. This means that our k8s files and docker files would need to be updated with the proper commands to install this library. 

We'll need to devise a way in which we can detect if full_text already exists with a file. If it does exist then we do things normally. 

If it doesn't exist, then we need to generate it using Tesseract. 

Tesseract will need to know what language the document is in. We may be able to use the "Language" field from the form to determine what language to run the OCR in.

After ingest, a worker will need to be fired off to run the OCR, generate the file, then use the files contents to index the data into the full text field.

We'll need to make a determination on whether or not we would like to keep the ocr text file around as a derivative. If we keep it around, then we will have to look into an update mechanism which would update the contents of the OCR derivative text file. We would also have to update the index. 

We'll need to make sure to keep a close eye on the delimiters in the file and any should be scrubbed out. I.E \n \r etc.

**Comment by decimalator** [comment]
it wouldn't be any different than any other gem with native extensions, right @straleyb ? I think you just add to the Gemfile and it will get compiled on the `bundle` portion of the container spinup process

```
    spec:
      containers:
        - args:
            - bash
            - -c
            - './build/entrypoint.sh && bundle exec rails s puma -e production'
```

The `./build/entrypoint.sh` script gets run each time the container boots. That runs various things that should do the job of getting any gems compiled that aren't already built

**Comment by straleyb** [comment]
Its not a gem. Its a library that will need to be compiled from source. 

https://github.com/tesseract-ocr/tesseract

**Comment by jechols** [comment]
Adding this to our standard worker image pretty much means adding it to the main image.  I don't see it being a problem in any way, though it's even more bloat in an already bloated setup.

It may be time to start considering how much the web image really needs of the workers' apps.  It may be the case that we can run slightly slimmer if we only put things like this into a worker-specific image.

The tougher part as I see it would be detecting OCR and *not* running a process.  If something is a TIFF, it won't have OCR embedded as far as I know, so that's easy.  But PDFs... those would require some kind of `pdftotext` invocation followed by checking what comes out maybe?  In some cases there may be embedded text that's just garbage, and rerunning OCR is the way to go.

I think this is going to be a pretty big chunk of work if it's not feasible to just say "OCR all images and PDFs".

**Comment by CGillen** [comment]
Since pulling in #1129 I was easily able to do the following

1. Rebuild docker images `docker-compose build --build-arg UID=$(id -u) --build-arg GID=8083 server workers app test dev`
1. Add Non-text-searchable.pdf to application tmp directory
1. Convert Non-text-searchable.pdf to a high-dpi tiff `convert -density 300 Non-text-searchable.pdf -depth 8 Non-text-searchable.tiff`
1. OCR the tiff to many different formats `tesseract Non-text-searchable.tiff out (hocr|tsv|txt)

Note: I also tested with jp2 as tesseract input. Tesseract still needed the 300+ DPI density and 8-bit depth (can't be any higher). It managed to OCR just fine but threw a warning about an invalid DPI of 0. I guess it couldn't guess the DPI and fell back to assuming 70 DPI, but it worked regardless.

This was all straight forward and can easily be used for the MVP goal of getting the full text extracted into Solr for searching. The easiest way of course would be to OCR into txt format, read the file into memory, ship it off to Solr, and discard the txt file. This would prevent us from needing to keeping more derivative files around and managing future problems like presenting text in UV, which is likely to be a large problem.

Some thoughts on getting UV to display OCR'd text. We could derive the hocr file and ship it next to all the other derivative jp2s that RAIS is supposed to be aware of. Then we would need to upgrade RAIS to implement the [IIIF Search API spec](https://iiif.io/api/search/1.0/#table-of-contents) when an hocr file is present.

**Comment by jechols** [comment]
RAIS doesn't have any concept of the repository or object relationships, so it's not the place to implement a search engine.  Building a search into RAIS would effectively make our Hyrax layer redundant... and while I'm all for ditching the stack, I think that may be a bit overzealous even for me :)

No, the search endpoint has to exist at a level where the search terms can be sent to solr with all the context we rely on, such as what works are discoverable by the current user.  Then the app has to process what solr returns in order to respond with the appropriate IIIF information.  It's not just responding that "image X has this at coord. (100,100) - (250,125)".  It has to tell the client where in Oregon Digital the asset is found - which IIIF manifest, the canvas URL, stuff like that which only the DAMS will be able to piece together.

This means that we can't just index raw text and then discard it - we have to store word coordinate data and we have to be able to process it in some way in the Rails application in order to return the IIIF Search response.  I would expect something like this already exists in the Hyrax ecosystem, though.

**Comment by CGillen** [comment]
Wow, I had a big derp when I was writing that up. For some reason I thought RAIS was providing all our IIIF functionality. Of course not, duh. Whatever is writing our IIIF Manifests is where we need to add the search API implementation.

**Comment by CGillen** [comment]
It looks like figgy stores ocr and hocr content into solr then implements a method for parsing the hocr field to display the results in the correct coordinates. We can do the same pretty easily I imagine.

The MAJOR problem we have right now with `blacklight_iiif_search` is that it expects (and I think this is reasonable and might be partly tied to the iiif presentation spec) every canvas to have a unique ID and be a unique document in solr. In other words, every page we generate from a PDF should be a new fileset, or roughly similar.

This is important because the search needs to be able to reference a canvas to display the hit count on and the hit highlight. As it is, we can only display hit counts and hit highlights on the first page of every PDF and any hits in subsequent pages will also be displayed on the first page.

**Comment by CGillen** [comment]
I got `blacklight_iiif_search` working here: #1139 
It allows searches, returns the correct number of hits, but is still blocked by the above problem of canvas to solr document mapping.
It also has some hanging code for hOCR and displaying hit bounding boxes.

**Comment by jechols** [comment]
Making each page into a fileset will be difficult.  I've documented my struggles with making the setup work the way we want it to, but that documentation is probably in the form of comments on closed tickets...

One big issue was updating the PDF - since derivatives have no direct connection to each other, how do we make a PDF act like a "parent" such that all the pages are removed and regenerated after the PDF itself is removed or modified?  To be fair, that might be a problem right now - I can't recall how I implemented that brittle solution.  But in today's setup, the PDF is a real fileset, so removing all its derivatives should be simple.  If we had the PDF generating new actual filesets, things could get hairy without a lot of custom work.

I recall there being other pretty big blockers, but I'd have to dig some to find notes.  I'm sure I wrote all this stuff down in *some* ticket, but I can't figure out where....

**Comment by CGillen** [comment]
I'll have to read more into figgy and what they ultimately decided to do.

An alternative would be to go outside of hyrax land. If we create new solr documents for each page, we could include a parent relationship field. We're already expected to do a join on such a field to the parent work. We'd have to rewrite how the original iiif manifest renders, such that the canvas id references the new solr document's id not the fileset. The other concern would be in reindexing again, would we want to regenerate these custom documents? I don't think so, but maybe there is a reason to. I bet not reindexing them would be easier though.

**Comment by wickr** [comment]
Related to #1100

**Comment by CGillen** [comment]
QA:
- [ ] Ingest a new PDF (with selectable text)
- [ ] Wait for Universal Viewer on the new work page to start showing the PDF
- [ ] Search for a word in the PDF
  - [ ] Word is found
  - [ ] Word is properly highlighted
  - [ ] Multiple instances of the word is found
  - [ ] Word is found on different pages
- [ ] Repeat for a new PDF without selectable text (image of text)
- [ ] Wait for Universal Viewer on the new work page to start showing the PDF
- [ ] Search for a word in the PDF
  - [ ] Word is found
  - [ ] Word is properly highlighted
  - [ ] Multiple instances of the word is found
  - [ ] Word is found on different pages

**Comment by shieldsb** [comment]
QA fail. Words were not found during search for either work.

**Comment by CGillen** [comment]
QA from above is ready again
QA:
- [x] Ingest a new PDF (with selectable text)
- [x] Wait for Universal Viewer on the new work page to start showing the PDF
- [x] Search for a word in the PDF
  - [ ] Word is found
  - [ ] Word is properly highlighted
  - [ ] Multiple instances of the word is found
  - [ ] Word is found on different pages
- [x] Repeat for a new PDF without selectable text (image of text)
- [x] Wait for Universal Viewer on the new work page to start showing the PDF
- [x] Search for a word in the PDF
  - [ ] Word is found
  - [ ] Word is properly highlighted
  - [ ] Multiple instances of the word is found
  - [ ] Word is found on different pages

**Comment by shieldsb** [comment]
QA fail.

**Comment by CGillen** [comment]
QA:

- [ ] Ingest a new PDF (with selectable text)
- [ ] Wait for Universal Viewer on the new work page to start showing the PDF
- [ ] Search for a word in the PDF
  - [ ] Word is found
  - [ ] Word is properly highlighted
  - [ ] Multiple instances of the word is found
  - [ ] Word is found on different pages
- [ ] Repeat for a new PDF without selectable text (image of text)
- [ ] Wait for Universal Viewer on the new work page to start showing the PDF
- [ ] Search for a word in the PDF
  - [ ] Word is found
  - [ ] Word is properly highlighted
  - [ ] Multiple instances of the word is found
  - [ ] Word is found on different pages
- [ ] Attach either previous works to a parent work (or ingest a new one as a child)
- [ ] Wait for Universal Viewer on the new work page to start showing the PDF
- [ ] Search for a word in the PDF on the child page
- [ ] Search for a word in the PDF on the parent page
  - [ ] Word is found
  - [ ] Word is properly highlighted
  - [ ] Multiple instances of the word is found
  - [ ] Word is found on different pages

**Comment by shieldsb** [comment]
QA fail.  Words searched for not found in text or image.

**Comment by shieldsb** [comment]
QA fail.  Display of highlighted words does not function appropriately or consistently.
