### ISSUE TITLE
Universal Viewer - book objects have no side-by-side view option

### ISSUE THREAD

**Issue by raybrarian** [OregonDigital/OD2#1120]
### Descriptive summary

Example: https://staging.oregondigital.org/concern/documents/fx71bj55s?locale=en#?c=0&m=0&s=0&cv=4&xywh=-2966%2C0%2C8288%2C3794

Abigail Scott Duniway Diary. 
Is this a migration issue? A IIIF manifest issue?

### Expected behavior
Should look like:
![image](https://user-images.githubusercontent.com/4460510/78945080-49224880-7a74-11ea-99f0-ee9cd844f02c.png)

### Accessibility Concerns

None I'm aware of.

**Comment by wickr** [comment]
I thought there was a ticket for this already but I'm not finding it...

To enable this view is a config option in the Universal Viewer settings, and it's not on by default. I looked at enabling it a few weeks ago, but waited because the version of Hyrax we're on has an older Universal Viewer version, and also the location of the config file changed, so I was going to wait until we had updated to Hyrax 3 (which doesn't have an official release yet).

**Comment by CGillen** [comment]
Reviewed By: @petersec 
ready to be worked on.

**Comment by CGillen** [comment]
QA:
- [ ] Visit work page with multiple images (pdf is a good bet)
- [ ] See Universal Viewer has option for side-by-side display in top right
- [ ] Side-by-side display is chosen by default

**Comment by shieldsb** [comment]
QA pass.
