### ISSUE TITLE
New collection modal

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1158]
### Descriptive summary
A modal for creating a new collection, with or without a pre-populating works. This will be displayed from several places (save to modal #1150, and collection interface #1153).

### Expected behavior
Modal that presents a form for creating a new user collection. form may contain a hidden input for works to add to this collection.

### Related work
Part of #1144 
Depends on #1150 and #1143

**Comment by CGillen** [comment]
QA:
- [ ] `create new collection` button opens new modal from `save to...` modal
- [ ] New modal contains basic form for creating a collection
- [ ] Closing new modal dismisses itself and re-opens `save to...` modal
- [ ] Submitting new modal requires a title
- [ ] Submitting new modal creates a new collection, owned by the current user, containing the current work

**Comment by shieldsb** [comment]
QA pass. 

Note: when using chrome to created a collection the save button at the bottom of the collection creation modal is not visible and will not allow you to scroll down to it. I was able to see and successfully use the button in IE. The button is barely visible (can't see the word save) in Firefox, but enough so that I could click it because I already knew the function)
