### ISSUE TITLE
Standard size derivatives

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1235]
### Descriptive summary
Derivatives for files should include a "low resolution" or "standard size" for anonymous and unauthorized users to download, or other users to choose from if they have poor bandwidth or are searching for a standard format (like for graphic design).

### Expected behavior
Image formats:
~680px on longest side.~ 1080p. file format may be decided to be standardized by POSM later, probably jpg.

Sound formats:
.mp3, no notes on bitrate but can be assumed to need to be standardized by POSM later.

Video formats:
.mp4, I'm assuming a standard resolution like ~680px on longest side~ 1080p. No note on bitrate but can be assumed to need to be standardized by POSM later.

PDF/text formats:
no notes, discuss with POSM

### Related work
Blocks #1234 

### Accessibility Concerns
Preserving PDF text will be important

**Comment by jechols** [comment]
PDFs will need a *lot* of careful consideration before we go there.  Rebuilding a PDF that has embedded images can be a huge complication and there is a *lot* that can go wrong.  For our newspaper processes, we've had to pin to an extremely outdated, custom-compiled version of poppler utils in order to simply manage splitting pages and extracting text without problems.

**Comment by jechols** [comment]
This ticket needs a lot of clarification to get started:

General:

- Are we looking to have a single "medium" derivative, or are we trying to provide multiples?  "Low-bandwidth" doesn't mean the same as "standard" size to me.  e.g., an 8-megapixel image is very good quality (4k), but requires about half the bandwidth of a "good enough" quality one-minute 720p video.

Images:

- 1080p is defined as 1920x1080.  What do we want to do with images that don't fit that ratio?  Crop to that size?  Squash?  Center?  Or do we mean "1080px on the longest side" (which is definitely *not* 1080p)?  Or "Preserve the aspect ratio but make height 1080px"?
- Do we want to upscale small images to this size or try to build the derivative logic such that the standard size of a small image just redirects to the full image?

Audio:

- Specs are definitely needed for audio derivatives - bitrate has to be defined as well as things like: do we turn stereo to mono (1/2 the file size)?
- I'm not super familiar with all the knobs that can be tweaked for MP3 files, so somebody who knows more should probably make decisions here to ensure we're getting a "good enough" quality without blowing up the file size.
- Some of our audio is bound to already be at or below whatever bitrate / channels we define.  Do we want to try and add logic to avoid making derivatives for this?  (I'm not sure if/how to do this, but it could be looked into)

Video:

- Again, 1080p means 1920x1080.  What about videos that don't fit this ratio?
- 1080p videos are huge unless we do things like drastically cut the frame-rate, encode at a terrible bitrate, etc.  This won't be a "low-bandwidth download" and in many (most?) cases will be the same size as, *or larger than*, our source video.
- Do we want to upscale videos?  I assume not, but we do need some strategy when the video source is already below our "low-bandwidth" threshold.
- Every question about audio needs to be answered here as well, because video files need embedded audio in them.
- mp4 isn't a "standard format": it's a container format which can have a variety of data streams in it.  We have to decide on the data streams' codecs for both video and audio in the first place.  The codecs we choose will have an impact on compression ratio as well as compatibility with end-users.
- Beyond the codecs, we also need to choose other things like bitrate, frame-rate, maybe other size-shaving options?
- Same with audio: somebody who knows more about video should weigh in on the different options for quality vs. file size.

PDF:

- Obviously nothing can happen on PDFs until decisions are made, so I'm just noting that this can't move forward.

**Comment by jsimic** [comment]
This is already on the agenda for discussion by POSM on 8/12.

**Comment by mellinma** [comment]
POSM Review and recommendations 8/12/2020
**Images:**  1000px on the long side (to not confuse with 1080p) No cropping,no squashing, no upscaling 
**PDFs:** Make no derivatives, accept as is. 
(note: Some of the PDFs are gigantic, so we might consider breaking them into compound objects.  Splitting a PDF into separate things has an impact on searching within.  Some of our PDFs are already downscaled a bit to get them into OD.  When someone clicks the download, it might be nice to show the size of the file. Kate will check with Chris about whether that's ideal.)
**Audio** If the original file existing in OD is an MP3, pass it through.  Do not drop stereo to mono.  New MP3s will be 16 bit or higher. 44.1 kHz is the sample rate.  192 is the bit rate for MP3 (kbit per second).  Minimum standard from LoC is 96 kHz and bit depth 24)

**Comment by CGillen** [comment]
https://github.com/OregonDigital/OD2/blob/master/app/services/oregon_digital/file_set_derivatives_service.rb#L57
From discussion with @jechols this is where we should be able to define new output formats. We will need to pull in `create_audio_derivatives` and `create_video_derivatives` from Hyrax to add a new `outputs`. That new `outputs` should be our standard-size deriv and may be easily retrievable in a hyraxy way

**Comment by CGillen** [comment]
For POSM review: Audio and Video players will play at the standard quality by default. Do we want to present the archival copy in the page viewer? If so, remember that those files can be ripped from the page/browser

**Comment by jsimic** [comment]
Standard size what we want to present through the viewer. Archival size can be made available to download via download button.

**Comment by jsimic** [comment]
Will QA post refresh

**Comment by shieldsb** [comment]
QA pass for audio, text, image.  QA fail for video, it scales up the size of the mp4 files.

**Comment by CGillen** [comment]
@jsimic I need a point of clarification:
`If the original file existing in OD is an MP3, pass it through, don't reformat or upscale.`
Does this mean all MP3, OD1 and OD2, or only MP3s from OD1? If only OD1, how do we determine that?

**Comment by jsimic** [comment]
@CGillen All mp3, from OD1 as well as new content added to OD2
