### ISSUE TITLE
Works without identifier can not be added to collection (or otherwise saved)

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1237]
### Descriptive summary
Adding a work to a collection causes the work to be saved without going through the form. This causes problems when the work is missing required metadata. The only field that seems to be causing this issue from time-to-time are some worms are missing an identifier.

These are either old works that had problems with migration early on (before form validation checks) OR recently saved works that encountered an error with our Hyrax 3.0-RC1 upgrade. Depending on the root of the problem, either we should do #815 or develop new code to make sure identifiers are acting properly and remediate the existing works.

### Expected behavior
Exploration is done to see what the root problem is and a solution is devised and implemented accordingly. Works will not exist without an identifier and other required metadata. Saving a work will not cause a crash

### Related work
This blocks/impedes Service Manager work review

**Comment by straleyb** [comment]
This has been deemed a non-issue. The fix for this is unnecessarily complicated for this issue. The issue was simply, early on, these works got created without the required fields. This should never happen now. Since they dont have the required fields, when the collection adds the works to itself, it saves the works to complete the relationship. Since the works CANNOT SAVE DUE TO MISSING REQUIRED INFO, it breaks. This should resolve itself and we are closing this for now.
