### ISSUE TITLE
Design for Work Show page

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1326]
### Descriptive summary
The work show page features many distinct elements of functionality and some of these have been removed, reworked, or redesigned

- Collection block, top-left
  - If possible, display in the context of coming from a collection landing/search page
  - If not, display first collection for now
- Save to... functions same as it does now
- Download to be a dropdown to select between
  - Download (full res)
  - Download (standard res)
  - Metadata (CSV)
  - Embed (UV iframe code)
- Tabbed content
  - Details (metadata)
  - How to cite (citation formats)
  - *Can I use this?* (new tab for copyright information)
- Explore more is removed

### Expected behavior
The work show page looks and feels like the MAC design.

Latest MAC Design: https://projects.invisionapp.com/share/47X400SV3BM#/screens/415938487

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by straleyb** [comment]
QA:
- [ ] Copyright link next to title
- [ ] Save to and download buttons next to each other
- [ ] Edit and delete buttons next to each other
- [ ] 2 column layout for descriptions/metadata
- [ ] citations under how to cite tab
- [ ] If work has parent, parent should display parent under Contained in
- [ ] if work has children, children should display under Contained In This Object
- [ ] if work has siblings (works in same parent work) it should be displayed under Related items

**Comment by shieldsb** [comment]
QA fail. 

- The save to and download buttons over lap.  The save to button does not have a box around it unless you hover over it, which does not match the wireframe. 
- Should the edit button be framed too? 
- There is a 2 column layout, but they overlap.  The font and text size do not match the wireframes. The order of the fields does not match the wireframe layout. 
- Currently the tab next to cite says "Description" the wireframe says "Details" 
- Collection name, number of items, etc. and logo not displayed at the top of the page about the work title. 
- The items under Contained in This Object are not linked, and the spacing between text and object needs to be reviewed. 
- For oral history complex objects, no images display at top of page, only in the Contained in This Object section 
- Unable to test parent and sibling based on what is in OD2, and I'm having trouble adding a complex object but will keep working on it.

**Comment by straleyb** [comment]
For some of this QA, the issue spawns from the application not adhering to both browser zoom AND computer settings of fonts being larger than 100%. This ticket is related to some of this, particularly the metadata overlap and the buttons overlapping. 

#1387

**Comment by straleyb** [comment]
> QA fail.
> 
> * The save to and download buttons over lap.  The save to button does not have a box around it unless you hover over it, which does not match the wireframe.
Overlapping bug here #1387 
> * Should the edit button be framed too?
Fixed by #1389 
> * There is a 2 column layout, but they overlap.  
Overlapping bug here #1387 
> The font and text size do not match the wireframes. 
Fixed by #1389 
> The order of the fields does not match the wireframe layout.
Discussion?
> * Currently the tab next to cite says "Description" the wireframe says "Details"
Fixed by #1389 
> * Collection name, number of items, etc. and logo not displayed at the top of the page about the work title.
> * The items under Contained in This Object are not linked, and the spacing between text and object needs to be reviewed.
linking Fixed by #1389 spacing needs review
> * For oral history complex objects, no images display at top of page, only in the Contained in This Object section
> * Unable to test parent and sibling based on what is in OD2, and I'm having trouble adding a complex object but will keep working on it.

**Comment by shieldsb** [comment]
- The save to and download buttons over lap. The save to button does not have a box around it unless you hover over it, which does not match the wireframe. Overlapping bug here #1387

- Should the edit button be framed too? Fixed by #1389
Probably need space between the edit button and file manager button below. 
![image](https://user-images.githubusercontent.com/53542788/99722500-97191900-2a65-11eb-9b9b-025f56d80b3c.png) 

- There is a 2 column layout, but they overlap. Overlapping bug here #1387

- The font and text size do not match the wireframes. Fixed by #1389

- The order of the fields does not match the wireframe layout. Discussion? 
This might be a question for metadata. 

- Currently the tab next to cite says "Description" the wireframe says "Details" Fixed by #1389
Complete 

- Collection name, number of items, etc. and logo not displayed at the top of the page about the work title. 
Collection title should be bolded in top header. 
![image](https://user-images.githubusercontent.com/53542788/99723149-a5b40000-2a66-11eb-8631-c38866896593.png)

- The items under Contained in This Object are not linked, and the spacing between text and object needs to be reviewed. linking Fixed by #1389 spacing needs review 
Links now working. Spacing needs to be reviewed by POSM? 

For oral history complex objects, no images display at top of page, only in the Contained in This Object section
Unable to test parent and sibling based on what is in OD2, and I'm having trouble adding a complex object but will keep working on it.


![image](https://user-images.githubusercontent.com/53542788/99722500-97191900-2a65-11eb-9b9b-025f56d80b3c.png)

**Comment by jsimic** [comment]
As per ticket #764 metadata fields are ordered in https://docs.google.com/spreadsheets/d/14xLkWt8KI9jCdlvPrNATgORngJEhXKOCoV0LAew1BQ4/edit#gid=1891520168 

The wireframes are in the OD1 order and incomplete, and have been modified by Metadeities.

**Comment by shieldsb** [comment]
QA pass.
