### ISSUE TITLE
Visibility settings for ingest

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#1350]
### Descriptive summary

There needs to be a way to configure visibility settings for bulk ingest in the structured metadata. 

### Expected behavior

At ingest, the metadata will have a field for visibility settings and values that correspond with OD2 visibility settings: open, UO, OSU, lease, embargo, and restricted.

### Related work

This will be configured for a visibility facet for admins: https://github.com/OregonDigital/OD2/issues/1351

### Accessibility Concerns

N/A

**Comment by wickr** [comment]
QA after bulkrax is added.

**Comment by straleyb** [comment]
Looks like this just needs a QA. The answer to @wickr question is that it sets it for each work. Currently it detects whether or not a visibility row exists and then sets the data on the work based on that. If no visibility is in the row it sets it to default as open. If we want to set the visibility for the entire importer there would need to be some over arching updates made to bulkrax in the way it handles creating the importer. Otherwise the data can be copied down the column in the csv and itll just handle it on a per work basis.

https://github.com/OregonDigital/OD2/blob/master/config/initializers/bulkrax.rb#L161-L175 Here is the relevant code that handles visibility
