### ISSUE TITLE
[MVP QA Fail] Edit collection information (such as label, thumbnail, etc)

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1373]
### Descriptive summary

UI for creating collections, editing information, setting a label. May be included in Collections Extensions work being done by community.

### Expected behavior

Create a new collection in the dashboard
- [ ] Add required fields and at least one value in a field that requires a URL
- [ ] Confirm collection appears in front end

Edit an existing collection in the dashboard
- [ ] Add fields, including at least one value in a field that requires a URL
- [ ] Confirm changes in the front end

### Related work

#43, #142, #267, #268,  #341, #359, #614, #757, #1101

**Comment by carakey** [comment]
### QA procedure:
_Signed in as cara.key@osu (admin)_

- New Collection > Digital Collection
- Complete fields marked _required_ (Title only) as well as Description field.
- Add Creators from lc, wikidata, opaquenamespace (all successfully fetched correct label). Attempt to input bad data (all rejected).
- Save Collection. __FAILS HERE:__

  - Got "Ack" message when clicking Save on new collection. 
  - From dashboard: Collection was visible, with only one Creator listed (three were entered, only the first appeared, which was an LCNAF term fwiw). 
  - On Public collection landing page, Description field content was visible, but no Creators. 
  - Got "Ack" again when trying to go to Edit Collection, unable to edit. Deleted collection.
  - Reattempted above with only one Creator (from opaquenamespace) instead of three. Same results, except zero Creators visible from dashboard. Deleted collection.

- Reattempt above with only Title and Description complete. Collection saved successfully. 
- Verify collection appears in front end. Description and Title present as expected.
- Return to Dashboard and Edit Collection. Description and Title fields populate as expected.
- Edit Description and add a value in a URI field (Creator, using LCNAF value from previous attempt) __FAILS HERE:__

  - "Ack" message again when clicking save on edited collection.
  - Creator label and edited Description appear on Dashboard view.
  - Edited Description does appear on Public collection landing page. 
  - "Ack" message when attempt to Edit Collection.

### Additional Notes

- Title is currently the only required field; Metadeities to discuss required fields for collections.
- Form should be updated with latest helptext - #1307

**Comment by jsimic** [comment]
Creation and editing of collection appears to be working on the backend but cannot confirm successful metadata creation/edits until collection landing page is in line with wireframes and all metadata fields are showing. See #437 and #1476

**Comment by jsimic** [comment]
Working!
