### ISSUE TITLE
[MVP QA] Validate edited/changed data

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1383]
### Descriptive summary

This is used by the bulk ingest, single ingest form, and any editing. We need to figure out what validation is actually happening in current OD, and use this as a basis for this implementation. 

### Expected behavior

Form
- [x] Browse/search for an extant work
- [x] Add a value to a field requiring a URL (see MAP)
- [x] Add a value to a field that requires a date (see MAP)
- [x] Add a value to a field that requires text (see MAP)
- [x] Change or add a file to the work
- [x] Change or add an oEmbed to the work
- [x] Confirm field values have been updated (with correct label on front end and the more info icon links to the external authority for URL-requiring field)
- [x] Confirm field values appear correctly in nts
- [x] Confirm file now appears in fileset with correct data
- [x] Confirm derivatives (thumb, standard size) and full size files are visible and downloadable
- [x] Confirm oEmbed is visible/playable

Bulk
- [x] Browse/search for an extant work(s), use Exporters to download csv
- [x] Add a value to a field requiring a URL (see MAP)
- [x] Add a value to a field that requires a date (see MAP)
- [x] Add a value to a field that requires text (see MAP)
- [x] Change or add a file to the work
- [x] Change or add an oEmbed to the work
- [x] Confirm field values have been updated (with correct label on front end and the more info icon links to the external authority for URL-requiring field)
- [x] Confirm field values appear correctly in nts
- [x] Confirm file now appears in fileset with correct data
- [x] Confirm derivatives (thumb, standard size) and full size files are visible and downloadable
- [x] Confirm oEmbed is visible/playable

### Related work

#35, #42, #45

**Comment by CGillen** [comment]
Some additional QA should include checking validation of fields with data that should not be allowed. This could be different between the Form and Bulk but some ideas are below:
- [ ] Attempt to add text to a field that requires a date
- [ ] Attempt to add text to a field that requires a URI
- [ ] Attempt to add non-URL as an oEmbed

**Comment by sseymore** [comment]
MVP QA #1355 Test Parent work: https://staging.oregondigital.org/concern/images/5t34sj64h?locale=en 

As of 2020-12-09:

- Oembed isn't working- will try later
- Not sure how to access .nts in OD2

QA fail: Attempt to add text to a field that requires a date

**Comment by sseymore** [comment]
https://github.com/OregonDigital/OD2/issues/1414

**Comment by sseymore** [comment]
https://github.com/OregonDigital/OD2/issues/360

**Comment by sseymore** [comment]
https://github.com/OregonDigital/OD2/issues/1413

**Comment by shieldsb** [comment]
Waiting for Bulkrax

**Comment by sseymore** [comment]
Notes:

-The exporter was designed for larger data exports, not single works, so I downloaded the CSV and file directly from the work showpage and then used the importer to do QA steps. 
-Ticketed up single work selection in the exporter as an enhancement: https://github.com/OregonDigital/OD2/issues/2697 
-oEmbed support was not QA'ed because that is also an enhancement and was not part of N8's original work for us. See Ryan's comment here: https://github.com/OregonDigital/OD2/issues/1408

**Comment by sseymore** [comment]
More notes:

-Was able to change/update metadata with bulkrax workaround, but not working as expected. 
-We cannot QA for file replacing or oEmbed right now due to other errors in code. See: https://github.com/samvera-labs/bulkrax/issues/709
-As mentioned above, the exporter cannot navigate to single items for export. 

QA has to be on hold for now until these issues are addressed. @jsimic @shieldsb

**Comment by wickr** [comment]
Believed to be complete, reworking of verification tasks for newer content is happening in newer tickets such as https://github.com/OregonDigital/OD2/issues/3031
