### ISSUE TITLE
[MVP QA] oEmbed Support

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1408]
### Descriptive summary

Features needed: Supporting externally hosted viewers and content from other platforms. Could have a record with metadata and instead of a file, an oEmbed URL (iFrame). There may be a Blacklight gem we can use for this purpose

### Expected behavior

- [x] Add oEmbed to item record 
  - [x] In web form 
  - [ ] In bulk ingest
  - [x] Confirm link is saved in record 
  - [x] Confirm embedded object appears on frontend item page 
  - [x] Confirm embedded object plays/is navigable 

Note: see #1378. Panopto is not working yet (2020-12-07)

### Related work

#75,   #76, #77, #97, #113, #169, #174, #190, #191, #195, #197, #207, #208, #209, #247, #1316, #1346, #1378

**Comment by sseymore** [comment]
when trying to access manage oembeds: ACK! LOOKS LIKE OREGON DIGITAL IS TEMPORARILY BROKEN. TRY AGAIN LATER AND LET US KNOW ON THE CONTACT FORM HOW YOU WOUND UP HERE.

**Comment by sseymore** [comment]
https://github.com/OregonDigital/OD2/issues/1413

**Comment by wickr** [comment]
Talking with @lsat12357 and @sseymore 
Given oEmbed handling is a special case since it's attached to FileSet metadata, we don't currently have a way to support this in bulkrax. I think it can be added, but the thought for MVP is that demand for this is very low. As long as oEmbed works reliably, it's editable in the UI, and we can write other scripts if we have a batch of URLs to add.

I think we can change the bulkrax/oEmbed support to be an Enhancement. Any objections @jsimic @shieldsb  ?

**Comment by jsimic** [comment]
No objection

**Comment by sseymore** [comment]
QA pass.
