### ISSUE TITLE
Multi-select facets do not always display selected values

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1422]
### Descriptive summary
Facet values are always sorted by amount, then alpha-numeric. This is confusing when a use selects a value and it falls off the display and is pushed into show more.

### Expected behavior
Facet values that are selected should be pinned to the top of the facet and not consume one of the 5 visible facet values.

### Related work
From QA: #1409

**Comment by shieldsb** [comment]
The two with 11 results are not sorted alphabetically. 
![image](https://user-images.githubusercontent.com/53542788/160517809-a9bbc302-b033-40b3-8939-5c79c7beadce.png)

However, a different search showed the same terms in alpha order
![image](https://user-images.githubusercontent.com/53542788/160518055-9501b937-4376-4d64-b0e3-60d9ed18880b.png)


Not sure if this matters but on the creator, it looks like it's sorting by first name instead of last when the same number of results are shown on the facet. 
![image](https://user-images.githubusercontent.com/53542788/160517684-7c316118-44b1-487e-bc49-2c51bdf77211.png)

Ok, so maybe not by first name either 
![image](https://user-images.githubusercontent.com/53542788/160518145-3072e68f-9a55-47ad-8cfc-87a0bd91010e.png)

**Comment by shieldsb** [comment]
QA pass. Noticed that it is using "the" as part of the sort order. 
![image](https://user-images.githubusercontent.com/53542788/169730315-565d7ecf-41ff-4c98-9752-b798f59409a8.png)
