### ISSUE TITLE
Collections ranking in search results

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2#1478]
### Descriptive summary

Creating this ticket for a future discussion about how collection records are ranked in the search results. 

### Expected behavior

Collection records in search results will or will not have some sort of ranking logic.

### Related work

N/A

### Accessibility Concerns

N/A

**Comment by jsimic** [comment]
In addition, we can consider calling out whole collections [similarly to Primo](https://search.library.oregonstate.edu/primo-explore/search?query=any,contains,data%20research&tab=default_tab&search_scope=everything&vid=OSU&offset=0) if user searches meet a threshold for strong matches to collections metadata.

**Comment by sseymore** [comment]
Similar to https://github.com/OregonDigital/OD2/issues/236

**Comment by CGillen** [comment]
Similar to #236 but not the same

**Comment by CGillen** [comment]
https://solr.apache.org/guide/7_6/the-dismax-query-parser.html#bq-boost-query-parameter

**Comment by wickr** [comment]
POSM decided to start lightly boosting collection titles, and if successful, could move on to more collection metadata fields such as Description, where additional names and keywords may be present.

I was originally thinking of index-time boosting, since we know which titles come from Collections in the app as we index. But it looks like that was deprecated in Lucene. Though there is a document score field option. We could maybe add a value to a new field if it's a Collection, and indirectly boost - though that may be for the whole solr document.

Though if we do a boost as part of the query, for title and for anything that has a Collection type in the model field, perhaps that would work. 
https://cwiki.apache.org/confluence/display/solr/SolrRelevancyFAQ#SolrRelevancyFAQ-FieldBasedBoosting

Here's 2 examples for testing, probably need more:
* Building Oregon coll comes up 2nd result: https://oregondigital.org/catalog?utf8=%E2%9C%93&search_field=all_fields&q%5B%5D=building+oregon#content
* Gerald Williams coll is 2nd result: https://oregondigital.org/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q%5B%5D=gerald+williams#content

Collection should probably be the 1st result instead of the 2nd.

**Comment by wickr** [comment]
I tried modifying an existing search results query to add in a boost but didn't have any luck:
`https://oregondigital.org/catalog?utf8=%E2%9C%93&search_field=all_fields&q%5B%5D=building+oregon&boost=if(termfreq(has_model_sim,%27Collection%27),5,1))`

Seems like it should work, but maybe not being passed through blacklight.

Also found this to be a good explainer: https://nolanlawson.com/2012/06/02/comparing-boost-methods-in-solr/
