### ISSUE TITLE
[Wireframe][Work Show] Collection preview links to file set page

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#1536]
### Descriptive summary
https://staging.oregondigital.org/concern/generics/df727084j?locale=en
The collection preview in the top-right links out to the file set page, it should link to the work show page.
![image](https://user-images.githubusercontent.com/11052958/108758321-cd9c7f00-74ff-11eb-8134-f1fbde83059e.png)

### Expected behavior
User is taken to the work show page when they click on the work preview within the collection preview

### Accessibility Concerns
Links of images need special attention for a11y. Alt text or screen reader hidden title within the anchor tag:
`<a href="..."><span>title</span><img src="..." /></a>`

**Comment by jsimic** [comment]
I have my doubts that anyone would click on a thumbnail with no other identifying information and expect to go to a work show page given that the context of the thumbnails are illustrative of the collection. Makes more sense to me that they'd expect to go to the collection landing page. Just as if in Explore Collections clicking on the thumbnail would take you to the collection landing page rather than the specific work.
