### ISSUE TITLE
[SEE #155] [1] UO Login Via Saml

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#173]
### Descriptive summary

We will be using the gem https://github.com/toyokazu/omniauth-shibboleth which will hook into omniauth and allow for authentication through the shibboleth system. This will live next to devise and CAS as another login option. It should create a new user that doesnt exist in the system, or login a user that exists. 

This has changed to use Saml instead of Shib.

**Comment by straleyb** [comment]
Waiting on Saml cert and UO IS team to make us a truster authority

**Comment by straleyb** [comment]
QA TESTING: Login using the UO login choice and login use University of Oregon credentials

**Comment by CGillen** [comment]
Still to do:

- [ ] Generate self-signed with a long expiry date x.509 cert and private key: https://www.akadia.com/services/ssh_test_certificate.html
- [ ] Upload cert & key to server
- [ ] Configure `:certificate` and `:private_key` omniauth_saml settings accordingly

**Comment by vantuyls** [comment]
@CGillen @straleyb please move this out of the QA column if it is not ready for QA

**Comment by straleyb** [comment]
Still waiting on generating certs, getting the certs onto the staging server, then configuration in the app

**Comment by CGillen** [comment]
Looking over to-do and what actually needs to happen, I guess cert and private key don't actually need to be on disk. It could (should?) be in the environment so we can pull easily pull it into config, like we do for everything else.
@revgum or @decimalator Can we get an x.509 cert & key into env? Or should we be looking at pushing a key to disk and reading in? Did we ever resolve secrets management?

For specificity, "long expiry date" should be on the order of the life of the product. 10+ years. We don't really want to have to touch it again and it's not something that's supposed to rotate.

**Comment by revgum** [comment]
- [ ] Add `SAML_ISSUER` and `SAML_PRIVATE_KEY` to ENV
- [ ] Add `private_key` and related ENV, and move hardcoded string to use `SAML_ISSUER` ENV at https://github.com/OregonDigital/OD2/blob/790edad475004fc6420555d5813f17bcc0916a5f/config/initializers/devise.rb#L257

**Comment by CGillen** [comment]
UO central IT has responded and setup is complete on the IdP side.
We're still experiencing issues from the application side. Checking the difference between SAML requests from a working application and ours, one or more are probably the problem:
- Our request's "AssesrtionConsumerServiceURL" property doesn't match what we have in our [metadata.xml](http://od2-staging.library.oregonstate.edu/users/auth/saml/metadata) because Hyrax insists on appending "?locale=en"
- Our request is missing the "ProtocolBinding" property
- Our request is missing the "NameIDPolicy" property

**Comment by CGillen** [comment]
According to logs from central IT and some troubleshooting between us, decryption on our end was not functioning properly. To have IdP decryption working properly, `SAML_PRIVATE_KEY` envvar is supposed to be set to a private key that matches `SAML_CERT`'s certificate. Both should include headers and footers.

Also, we are running into issues with what SAML attributes we're expecting and how they map to devise/omniauth properties.

**Comment by CGillen** [comment]
#321 Introduced some fixes from my limited ability to do local testing. Needs QA after pushing to staging

QA:
- Visit main page and click "UO Login"
  - [ ] Does not give `The login service was unable to identify a compatible way...` error (metadata issue)
  - [ ] Directs to UO Shib sign-in page
- Enter valid duckID and password
  - [ ] Redirects back to OD2, not an error page (Not 422 response) (CSRF issue)
  - [ ] Toast is not an error about `Invalid ticket` (Could be many issues, likely digest/signature validation)

**Comment by CGillen** [comment]
FFS. Apparently CAS has a "begins with" matching policy for the AssertionConsumerService metadata where Shibboleth does not. Compounding, Ruby-SAML uses a method that will dynamically change the URL depending on how the metadata and login entrypoint are accessed, which are likely vastly different in Hyrax because they force the locale parameter at in unoverridable level of the Rails engine.

All this boils down to this method needs to be override: https://github.com/omniauth/omniauth/blob/master/lib/omniauth/strategy.rb#L444
Taking out `query_string`

**Comment by raybrarian** [comment]
All QA passes - login link goes to UO Shib, can login and see admin interface successfully.
