### ISSUE TITLE
Stop devise from submitting plaintext password when logging in.

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#187]
### Descriptive summary

The app is posting the password for the user in the form. This is VERY bad. If you login, look at the developer tools under network. Click all, and check sign_in?locale=en, scroll down to the bottom and you can see the plain text password in the form data. We need to make sure this doesnt happen.

**Comment by wickr** [comment]
Possibly related: https://github.com/OregonDigital/OD2/issues/188

**Comment by decimalator** [comment]
This is still the case with the current version on staging

<img width="1359" alt="Screen Shot 2019-10-08 at 11 09 01 AM" src="https://user-images.githubusercontent.com/1882223/66421132-28d9da00-e9bc-11e9-9cec-8671a3dc23a2.png">

This should only be the case for non-SAML local logins.

**Comment by raybrarian** [comment]
Hey @straleyb - looks like this is something Features needs to take on. Thanks!

**Comment by CGillen** [comment]
As far as I'm aware this is perfectly normal behavior. How else would a user authenticate with a server? It's TLS' responsibility to protect data from prying eyes, not the application's. Once the application has a secure connection it should have the freedom to transmit whatever sensitive data it wants. One of the many exceptions, of course, being we shouldn't put those secrets in an openly shared location, like query parameters. Form POST data and request headers are explicitly not shared for THIS exact reason.
Logging is a different story and is why #188 was a problem.

You can convince yourself that this is industry standard (under the premise that Google follows best practices for at least their most basic services) by following the same method posted in this ticket to examine your GMail login flow or any other "well built" application on the web.
![image](https://user-images.githubusercontent.com/11052958/66927487-be8cef00-efe4-11e9-9951-2d944b36f22c.png)
If you're still not convinced, do it for your bank and prepare for a shock (note: not MY bank).
![image](https://user-images.githubusercontent.com/11052958/66928941-07de3e00-efe7-11e9-9372-ef0f3f0198f1.png)


The caveat here, is obviously we need to be using TLS for all login submissions, but we should be doing that for the whole site anyways. It's 2019, come on. I'm going to close this as a non-issue unless someone wants to provide a thought experiment for reasonable abuse. In that case, contact me swiftly and discreetly because I've got a business proposition for you.
