### ISSUE TITLE
Contact us email labels for topic and message

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2053]
### Descriptive summary
The contact us email drops the topic and message in front of the user with no context. There should be a preceding label. @kmthorn @petersec will provide those labels

### Expected behavior
Emails for user contacting us has context surrounding the topic and message received.

**Comment by kmthorn** [comment]
E-mail message should read.

Thank you for contacting Oregon Digital.

We received a question from you about [ add the title of the item ].

You indicated that there was an issue related to [ add the type of issue ].

Your issue was: [ add the text the user provided in the form ]

Someone from the Oregon Digital team will reach out to you with an answer soon.

If you didn't make this request, please ignore this email, or contact us at oregondigitalref@uoregon.edu

Thank you,
The Oregon Digital Team

**Comment by straleyb** [comment]
Generate response email for only these two options.

**Comment by shieldsb** [comment]
Only one small, minor issue otherwise a pass. Add a line break after "Thank you," so that "The Oregon Digital Team" in on the line below it
![Uploading image.png…]()

**Comment by shieldsb** [comment]
QA pass.
