### ISSUE TITLE
My collection interface wireframes regression

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2070]
### Descriptive summary
My collection interface use to expose functions to users. It no longer does that. The interface should match the latest wireframes.

### Expected behavior
My collection matches wireframes and is usable by a user

### Accessibility Concerns
Buttons, links, and misc actions may easily break A11y

**Comment by CGillen** [comment]
QA:
- [ ] My collection has action buttons
- [ ] My collections closely matches wireframes: https://drive.google.com/drive/u/1/folders/17ePhe1m98-7_pcQ7uURBGJm-zcTRGmCK
  - [ ] list 
  - [ ] masonry
- [ ] Explore Collections closely matches wireframe: https://drive.google.com/drive/u/1/folders/1ndau6PwvxSDVrEG6Dj4Je1FgqGq6w_6CzcTRGmCK
  - [ ] list 
  - [ ] masonry
- [ ] My collection actions function

**Comment by shieldsb** [comment]
**My collections - Desktop**
List: selecting share gives an ack message instead of showing a link 
Masonry: under the collection title there are two separate lines in the WF, the first work edit, delete, export and the second for share.  Staging has all of these buttons in one block.  The test for these lines seems heavier in the WF, but that might not be an issue.  Again, no share link is displayed and share gives an ack message. 
**My collections - Mobile** 
List - same result with share function. WF doesn't include Show and dropdown to select # of items, but it is on the mobile version - guessing this is a WF problem  
Masonry - The formatting/spacing for the lines dividing edit, delete, export need adjustment. There are two separate lines in the WF, the first work edit, delete, export and the second for share.  Staging has all of these buttons in one block.   same result with share function. WF doesn't include _Show_ and the dropdown to select # of items, but it is on the mobile version - guessing this is a WF problem.

**Comment by CGillen** [comment]
My Collections:
- Share button is because user collections are configured as facetable but should not be. That should be fixed at next refresh/launch
- Ignored multiple blocks in favor of single blocks for action links because of a11y
- Show dropdown/search bar seems like a problem with the wireframes, it shows in a couple but not on any of the masonry for some reason

Explore Collections:
- Dates should appear in masonry once metadata exists

#2106 fixes the institution name
