### ISSUE TITLE
[3] Add validation to allow oEmbed media or regular media, but not both

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#208]
### Descriptive summary

Media added to a work and oEmbed media should not both exist on the same work.

### Expected behavior

Add validation to check that if media is already added to a work, oEmbed is not able to be added. 
If oEmbed is specified for a work, regular adding of media files is disabled for that work.

### Related work

#207

**Comment by CGillen** [comment]
I think easiest solution would be validation of presence on files and just present an error when saving w/ both present. Removing fields or tabs might be trickier but I'll need to play around in the code to see.

**Comment by CGillen** [comment]
@wickr I've looked over the work creation workflow and if we validate at the work model level, there's no way to know if files were submitted with the work since they attach later. I've tried validating for just oEmbed and no files, but the delayed file processing decides to clobber the validation process and save anyways, leaving us with invalid works. I'm still exploring validating at form submission but rails just isn't cooperating with me right now.

By default, Hyrax doesn't validate file presence anyways. It validates on the front-end that files are submitted with the form and we can do the same to exclusive-or w/ oEmbed media. We wouldn't run any more risk than we already do for form submissions. Our major risk increase comes from ingesting works with a direct-to-backend process, where we can already easily make works w/o files, but works w/ both would also be possible now.

**Comment by CGillen** [comment]
#1345 Added validation to the form that EITHER files were uploaded XOR and oEmbed URL was provided. It also coded such that the form initially doesn't support more than one oEmbed URL, but it should be able to handle being passed more than one and can display more than one, however probably poorly.

I think since Hyrax doesn't validate file presence outside the form, that should be good enough for now. We may want to add an additional check for no more files/urls when editing a work, if it has a url already.
