### ISSUE TITLE
New error messages for various server response codes

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2223]
### Descriptive summary
We need write-ups for these HTTP error codes:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

- 401: Unauthorized - You tried to access a resource you are not authorized (probably haven't authenticated yet) to view
- 403: Forbidden - You tried to access something we don't allow anyone to see.
- 404: Not Found - The resource you tried to access does not exist here. You tried to access a URL that doesn't exist
- 500: Internal Server Error - Something went wrong with the code on the server-side, usually resulting from some kind of crash
- 503: Service Unavailable - The server is down and (can)not accepting requests - For @decimalator to implement at the reverse-proxy level

Easter Egg:
- 418: I'm a teapot - My favorite response code, I cannot brew coffee because I am permanently a teapot OR a combo teapot/coffee maker that is temporarily out of coffee

### Expected behavior
Error messages are defined and implemented for each response code

### Related work
https://github.com/OregonDigital/OD2/issues/1721

### Accessibility Concerns
N/A

**Comment by jsimic** [comment]
401: Unauthorized
You have tried to access a resource that is restricted. Try logging in or registering for an Oregon Digital account, or contact us.

403: Forbidden
You have tried to access a resource for which you are not authorized. Contact us if you have questions.

404: Not Found
The resource you tried to access does not exist or has been moved. If you are using a bookmark or URL for direct access to the resource, try finding the item using the search box, or contact us.

500: Internal Server Error
Something has gone wrong with Oregon Digital. Please try again in a few minutes, or report the problem.

503: Service Unavailable
Oregon Digital is out of service or undergoing maintenance.

418: I’m a teapot
I cannot brew coffee because I am permanently a teapot or a combination teapot/coffee maker that is temporarily out of coffee

**Comment by jsimic** [comment]
Any "contact us" or "report the problem" should be a link to the contact form

**Comment by shieldsb** [comment]
QA fail. 

401 error does not match text above: 
![image](https://user-images.githubusercontent.com/53542788/196298589-35ecb2de-3811-45f7-be61-595930b9544e.png)

403 error does not match text above: 
![image](https://user-images.githubusercontent.com/53542788/196298186-4cadb60b-aecd-412a-8851-36583dd5b420.png)

404 error does not match text above: 
![image](https://user-images.githubusercontent.com/53542788/196299065-ab897434-0fcc-4f73-9012-c6c9d554afae.png)

503 error does not match text above: 
![image](https://user-images.githubusercontent.com/53542788/196298074-b4f70058-7f46-4ad2-9d06-2c6e8cf45137.png)

**Comment by carakey** [comment]
I wasn't meaning to QA this ticket, but noticed the 401 page needs a login link while doing QA on #2431.

If a user tries to access a work with restricted visibility, such as by a direct link, they get the 401 page that suggests they try logging in or registering, but the page does not include a link to log in or to register, and does not have the normal OD header with the login button, etc. If they got to the page by a direct link, they have no back button option. The "Contact Us" link works but is not obvious and does not route them back to the item. There is no clear pathway for them to log in and get to the item.

**Comment by shieldsb** [comment]
QA pass.
