### ISSUE TITLE
Correct fullsizeDownloadAllowed authority values

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2320]
### Descriptive summary

Fullsize Download Allowed authority values should be the boolean types 'true' and 'false' and not full URIs.

### Expected behavior

Authority values are only 'true' and 'false' following `xs:boolean` form

### Related work

#1596 

### Accessibility Concerns

N/A

**Comment by sseymore** [comment]
@wickr I am seeing this in the form with the correct boolean selections, so that's good, but not seeing the values in the works from recent migrations like CL Andrews works. In those works, in the form, that field is blank. 

Not sure if that's a separate issue. (maybe talk to @lsat12357 about this?) If it is, then I would say this passes QA.

**Comment by wickr** [comment]
QA pass
Authority values were updated. Problem @sseymore saw with the form was separate, #2347 and #2349 were the followups there.
