### ISSUE TITLE
Universal viewer 'jump to search result' not working reliably

### ISSUE THREAD

**Issue by carakey** [OregonDigital/OD2#2392]
### Descriptive summary

In Prod, on a text/PDF object, when searching within the text in UV and getting multiple hits, which are marked with blue flags along the bottom page scroll - clicking the blue search hit flag sometimes jumps to the page and sometimes does nothing. 

Other than "usually the first 2 or 3 clicks works and then after that it only rarely works" I can't prove a pattern. Same behavior in Safari and Firefox and in multiple items. 

![Screen Shot 2022-07-06 at 10 51 23 AM](https://user-images.githubusercontent.com/17655103/177612618-11611f8e-6cc2-4a1c-b9b5-5f16717b97a4.png)

Side note, the hover on the flags says "Page Page #". 

### Expected behavior

Clicking the flag for a search hit jumps to the indicated page.

### Related work

https://github.com/OregonDigital/OD2/issues/1450

**Comment by CGillen** [comment]
Ok, the issue here is clicking the bubble rather than the textbox. Apparently the clicking the bubble functionality has been disabled since 2017 for literally no reason. The code exists in UV, it's just commented out 🤷‍♂️ 
Guess we'll have to wait until the maintainers turn it back on. Until then, click the textbox
