### ISSUE TITLE
Do we need more roles than Managing, Depositing, and Approving?

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#24]
### Descriptive summary

This may need less work than previously expected. Roles exist by default in hyrax. These roles are Managing, Depositing, Approving. Managers have all the rights associated with an admin set. Depositing have access to be able to deposit into that admin set. Approving have the ability to review the works in a workflow within an admin set. 

Do we need anymore roles? If so, where do we put these roles, what are their privileges? Do we need to identify them? This is more of a question

Once we answer these answers, the role generation could be already complete. After that, we would need someone to go in and manage the admin sets and set up the proper users who have access to these admin sets.

**Comment by mccallum** [comment]
I've heard a fourth that might be up for discussion—Curating. The others match up as you mentioned:

- Managing - Administrator
- Approving - Archivist
- Depositing - Submitter

Is it worth considering a low-power role like "Member" instead of relying on login state? Thinking of the future. 

Advanced roles actual people for review are here: https://docs.google.com/spreadsheets/d/12ntAtn7GhSdXmUMsNg7hkKgyuvD9FYOBe2S4HvwS0IE/edit#gid=2107426351

**Comment by straleyb** [comment]
The answer is no, These roles will have to be broken up to be able to work between collections and admin sets and what not
