### ISSUE TITLE
Webform mismatch between uri and label

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#2634]
### Descriptive summary

When editing a record using the webform, I noticed in the Subject list that the labels of fetched terms do not match the URIs displayed. This may cause some confusion when adding or deleting terms.

<img width="688" alt="subjectURImismatches" src="https://user-images.githubusercontent.com/6344086/206531461-0e4b5a3c-7bfe-4dd1-b076-ac05312eaa15.png">

### Expected behavior

Labels and URIs should be matched. There may be mismatches is other fields, I haven't checked.

### Related work

[#500](https://github.com/OregonDigital/OD2/issues/500), [#34](https://github.com/OregonDigital/OD2/issues/34)

**Comment by jsimic** [comment]
@lamtu1  id.loc.gov is the Library of Congress. An overwhelming number of subject headings use it as do all the Creator fields and others.

**Comment by lamtu1** [comment]
@jsimic I just double check on the `Library of Congress`, it looks like it seems good on my end when double check on the URI and the label. But I do see that the Library of Congress update some of the vocab and changes the location in some of the word that use in the ticket. Below the images show:

<img width="686" alt="Screenshot 2023-11-14 at 2 40 48 PM" src="https://github.com/OregonDigital/OD2/assets/111306182/26f89fbc-ecba-425d-b3b4-de2b03aef871">

I think some of the event why some `Subjects` doesn't match up might be due to `LOC` move vocab around to a different URI. But I think this ticket can be QA as I am not seeing thing out of the ordinary.

**Comment by jsimic** [comment]
@lamtu1 I think it's unlikely that LOC moving terms around is the culprit. That usually happens if they move between /subjects/ and /names/ or a term is depreciated and a new record with a new ID is created to replace it. I'm hoping that this got taken care of earlier in development. The original record I was looking at still has the mismatch however: https://oregondigital.org/concern/images/df69h2447/edit?locale=en#Subjects. The first line with the label "Mythology, Classical" has the URI for "Gods" and vice versa.

**Comment by jsimic** [comment]
@lamtu1  The line in the record above labeled architectural interiors has a URI for a depreciated LOC term. That might be what happened--the label for the LOC term didn't get fetched because the record was depreciated and it just assigned the label of the next term to the URI, leaving the last URI without a label. We need to figure out some way of searching for these so they can be corrected...

**Comment by lamtu1** [comment]
@jsimic Would you want a separate ticket on this matter? and have it link to this ticket?

**Comment by wickr** [comment]
This seems related to this ticket:
https://github.com/OregonDigital/OD2/issues/2135

When the labels and URIs are prepared for display from a single property with multiple values, the pairing is broken and mismatches can occur. 

I see a different, also very wrong, alignment when checking the form:
![image](https://github.com/OregonDigital/OD2/assets/2293544/29f480e3-c69c-46af-ab54-6f3a22573f06)

It's going to vary. Sometimes it will even display right.

@lamtu1 this has nothing to do with LOC and is all on our end. We don't display the label/URI pairs reliably.

The good news is that labels are not saved this way on the record. But yes if you're trying to delete or check at all what values you have, you want to see the correct labels on the edit form (and anywhere).

**Comment by CGillen** [comment]
- [ ] Remove _tesim from parsable solr field
- [ ] Remove ‘no label found’ from parsable solr fields
- [ ] Change _sim fields used in advanced search combined search fields to _tesim

**Comment by CGillen** [comment]
@lamtu1 Next:

- Update the display in the `Data Sources` tab on the work show page (`GenericPresenter#zipped_values`). This gets out of sync with the old style of label parsing
- Update metadata download (`OregonDigital::MetadataDownload#metadata_row`). This does a lot of fetching and maybe other slow stuff. Examine each code path carefully and see if any can be sped up by not fetching labels or using local metadata services. It might mean you need to do a solr query but that's much faster all around.
- `OregonDigital::PresentsDataSources` has some methods that use zipping between uri & label solr fields
- Poke around for others, otherwise lets QA thoroughly

**Comment by lamtu1** [comment]
I will look through them and cleanup and update as much as possible as well poking around if any others are using the `zipped_values`
