### ISSUE TITLE
Work with quotes in title shows entity references in results Gallery view

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2658]
### Descriptive summary

Work with quotes in the title is showing the entity references in the Gallery view. List view is fine. Show page is fine.

![image](https://user-images.githubusercontent.com/2293544/209203235-fda79559-2b67-49a2-9c9f-9b15f069ef1e.png)
https://prod.oregondigital.org/catalog?f%5Bnon_user_collections_ssim%5D%5B%5D=osu-department-histories&locale=en&per_page=100&sort=date_dtsi+asc&view=gallery

### Expected behavior

Quotes render as expected.

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by straleyb** [comment]
I was looking for more like this to see if I could reproduce this error. Are there any others that you can find @wickr to help me pin point where the problem is? I noticed it was only that one and there are multiple works with quotes in their titles in that same collection so im curious if it has something to do with the work itself.

**Comment by shieldsb** [comment]
QA pass.

**Comment by wickr** [comment]
Fixed by #2680
