### ISSUE TITLE
Setup redirects from OD1 URLs to OD2

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#2742]
### Descriptive summary
Similar to #217, we need a way to redirect OD1 urls to OD2 style.

#### Current OD1 URLs:
  
- Work:                https://oregondigital.org/catalog/oregondigital:df70cf34f
- Collection:          https://oregondigital.org/sets/osu-scarc
- Work-in-Collection:  https://oregondigital.org/sets/osu-scarc/oregondigital:df70cf34f
- Image Downloads:
       https://oregondigital.org/downloads/oregondigital:df70dg549.jpg ##these come in with either ':' or '-' separator in the pid
       https://oregondigital.org/thumbnails/oregondigital-df70dg549.jpg
       https://oregondigital.org/media/medium-images/9/4/oregondigital-df70dg549.jpg
       https://oregondigital.org/media/thumbnails/9/4/oregondigital-df70dg549.jpg

#### Current/Default OD2 URLs:

- Work:                http://oregondigital.org/concern/videos/gm80hv32k
- Collection:          https://oregondigital.org/collections/rv042t060
- Work-in-Collection:  (no current Work view nested within Collection)
- FileSet:             http://oregondigital.org/concern/file_sets/g445cd121
- Image Downloads: https://oregondigital.org/downloads/f0df66x709b?file=thumbnail ##note 'f0' added to start of pid

This might be done best in two steps:
- At the nginx level, redirect OD1 urls to `https://oregondigital.org/concern/images/(:id)` for works and `https://oregondigital.org/collections/(:id)` for collections (sets). Use 301 permanently relocated
- Implement the work redirect from SA: https://github.com/osulp/Scholars-Archive/pull/1761/files

### Expected behavior
oOD1 Urls redirect to functional Urls in OD2

### Related work
#217
https://github.com/osulp/Scholars-Archive/pull/1761/files

**Comment by CGillen** [comment]
QA:
- [ ] Find a work
- [ ] Modify that work's URL to change the work type (/concerns/generics/<id> => /concerns/images/<id>)
- [ ] Be redirected to the original page, with correct work type URL

**Comment by decimalator** [comment]
### Overview

This here is the TL;DR version. I've included a lot more details about how traffic flows through the two systems, including a `mermaid` based chart of the service connection points. 

As long as all of the information that `nginx` needs to redirect the request is in the URL somewhere, we should be able to handle the redirects with `nginx` . We could re-use `od1/nginx-proxy` and deploy a `od2-prod/nginx-proxy`, but since BRPX can do all of that already and much earlier in the proxy chain that feels like the place to handle them. At launch it will mean that only the OSU Infrastructure team will be able to adjust the rules. We'll put together a mechanism to use files in the `OD2` repo to pull all of the rules from so we can use the same "deploy on merge" system we use for code changes. 

My biggest concern at first was how to differentiate between the different concern endpoints to use. Being able to send to the generic concern as long as the PID matches should make those pattern matches simple enough. I'll need to digest all of the different patterns, but so far everything looks more or less like the types of rules we already have experience with from previous OD incarnations. 

If we do run into URL patterns that require more information than is in the URL we'll have to handle those in Rails. Unless there are hints somewhere else in the request like the HTTP headers we would need some way for `nginx` to correlate PIDs with other identifiers. That's getting well out of what `nginx` is good at doing. 

I do have some questions that we'll need answers to below

### Questions

- [ ] How about `iip.oregondigital.org` URLs that go to `od1/iipsrv`? Do we have a way to translate those to something RAIS can respond to? Or will just OD1 requests generate `iip.oregondigital.org` requests? Should that domain stay pointed to the OD1 `iipsrv` deployment, or do we need to redirect those to corresponding `iiif.oregondigital.org` URLs to reach RAIS?

- [ ] How many of the OD1 redirects from the ContentDM to Hydra migration do we need to keep? We still have rules pointing to a `contentdm.oregondigital.org` service that doesn't exist anymore. I can't `ping` it, and it doesn't respond to HTTP or HTTPS. 

Where should we send requests for the ContentDM style URLs? Can we redirect those URLs to a specific endpoint in OD2? Or do we want to just continue let them try to proxy to `contentdm.oregondigital.org` and timeout?

---

### Background

Right now, pre-launch OD1 and OD2 both point to our Beavernetes Reverse ProXy, BRPX. The IP addresses that all of the OD1 and OD2 domains resolve to all point to our BRPX reverse proxy system, powered by `nginx`. When requests come in for OD1 and OD2 domains those domains are all configured to proxy the requests directly to the Beavernetes Ingress Controllers.

The Ingress Controllers handle all of the traffic into and out of the cluster. Without an Ingress Controller, your application is isolated within its "overlay network" that is only visible to other containers running on their physical worker nodes registered with the cluster. Requests initially reach the external IP addresses of BRPX nodes, which compares the DNS name of the request to decide where to send the request on to. 

The frontend BRPX proxy architecture is designed to overcome request timeouts that would happen if a user happens to get connected to a worker node that isn't fully running because of a reboot or some other failure. BRPX itself consists of a number of VMs running on OSU UIT's VMware system configured to coordinate the ownership of the various IP addresses that BRPX service. During normal operation about 50% of requests will hit one of the two BRPX nodes that currently provide the BRPX service. It does this through round-robin DNS records (multiple IP addresses for the same DNS name) and the `keepalived` services on each node that coordinate IP address ownership between the BRPX nodes. At the moment 2 nodes is plenty to handle the request load, but adding more nodes is relatively simple.

The Ingress Controllers use `Ingress` definitions to decide how to process incoming requests. We generally use host-based rules that direct requests for a specific DNS name (or names) to a specific Kubernetes `Service` in the same namespace as the `Ingress`. OD2 is one of the apps in Beavernetes with a little more complicated `Ingress` configuration. Requests with DNS names destined for OD2 DNS names choose the backend `Service` to connect the request to based on the URL path of the request. This allows us to direct requests to administrative endpoints to another `Deployment` of Rails dedicated to handling those specific endpoints. This helps keep most user traffic nice and responsive, even if OD2 team members are heavily using the admin dashboard, or the Sidekiq UI. 

OD1 you would think would be simpler with just a VM that runs some of its backend services itself. But it's not.

OD1's Rails, Redis and Memcache services still run on the original `lib-hydra1` VM. The Apache service on `lib-hydra1` acts as another reverse proxy level depending on the DNS name of the request. Rails and Resque talk to Fedora through `lib-hydra1's` Apache `mod_jk` plugin that communicates with Fedora's Tomcat via AJP instead of HTTP. 

When OD1 was originally developed the entire system ran on one VM, `lib-hydra1`. As it grew we moved components around, moving SOLR to a dedicated SOLR VM. We used a physical Linux server as `hydra-worker1` to run Resque jobs, etc. OD1 as it exists now all "works", but as we've seen that monolithic approach to web service delivery (any type of network service delivery!)  is difficult to scale with the traditional VM/server approach. The start of our OD2 development was the moment of truth as far as where we had to go to be able to run these complicated systems with any kind of guarantee of performance. 

As OD2 grew up we used some of its lessons to help OD1 limp along. Many of its backend services like SOLR, Fedora and the Resque workers run as `Pods` in Beavernetes in the `od1` namespace. There's a `tools` container that developers can run Rails console commands on to avoid further loading down `lib-hydra1`, but we've pretty much reached the limit of how much we can scale the system with a single VM running even just Rails.

OD2's design has evolved as we've learned better ways to deploy each of its various components to take advantage of the raw power of physical server hardware and the features of Kubernetes. 

OD2 requests are proxied directly from BRPX to the Beavernetes Ingress Controllers, which are configured to proxy requests for those domains to either the `od2-prod/web` or `od2-prod/web-admin` Deployments via their Kubernetes `Services`. 

Unlike OD1, these endpoints all link directly to the other containers in the cluster without more proxy hops. Each of the components use Kubernetes workloads like `Deployments` and `StatefulSets` to do its darn best to keep all of the containers in the workload running even if that means stopping the workload and assigning it to another worker node. Each workload communicates with other workloads through Kubernetes `Service` objects that act as a load balancer for each of the containers in the workload. This helps to provide very close to zero downtime for requests coming into the cluster even while their target workload is being restarted or updated, etc. 

Separating each backend component out to their own workloads allows Kubernetes to do most of the work of arranging and rearranging the containers across the cluster to give each container enough available resources to perform well and to take advantage of `Services` and other Kubernetes features to provide reliable and responsive network services. 

Below is a diagram of the different request paths for OD1 and OD2. 

```mermaid
  graph LR;
      BRPX --> Beavernetes-Ingress;

      Beavernetes-Ingress --> od1-nginx-proxy;
      Beavernetes-Ingress --> od1-iipsrv;
      Beavernetes-Ingress --> od2-web;
      Beavernetes-Ingress --> od2-web-admin;
      Beavernetes-Ingress --> od2-rais;

      od1-nginx-proxy --> lib-hydra1-apache;
      od1-nginx-proxy --> contentdm-oregondigital-org;

      lib-hydra1-apache --> lib-hydra1-passenger;
      lib-hydra1-apache --> od1-fcrepo;

      od1-fcrepo --> lib-mdb2-mysql;

      lib-hydra1-passenger --> lib-mdb2-mysql;
      lib-hydra1-passenger --> od1-mongodb;
      lib-hydra1-passenger --> od1-solr46;
      lib-hydra1-passenger --> lib-hydra1-redis;
      lib-hydra1-passenger --> lib-hydra1-memcache;
      lib-hydra1-passenger --> od1-iipsrv;
      lib-hydra1-passenger --> od1-fcrepo;
      lib-hydra1-passenger --> CVM;

      lib-hydra1-redis --> od1-workers;

      od1-workers --> lib-hydra1-redis;
      od1-workers --> lib-hydra1-memcache;
      od1-workers --> lib-mdb2-mysql;
      od1-workers --> od1-solr46;
      od1-workers --> od1-mongodb;
      od1-workers --> od1-fcrepo;
      od1-workers --> CVM;


      od2-web --> od2-fcrepo;
      od2-web --> od2-pgsql;
      od2-web --> od2-solr;
      od2-web --> od2-blazegraph;
      od2-web --> od2-redis;
      od2-web --> od2-memcache;
      od2-web --> od2-rais;
      od2-web --> CVM;

      od2-web-admin --> od2-pgsql;
      od2-web-admin --> od2-solr;
      od2-web-admin --> od2-blazegraph;
      od2-web-admin --> od2-redis;
      od2-web-admin --> od2-memcache;
      od2-web-admin --> CVM;

      od2-workers --> od2-redis;
      od2-workers --> od2-pgsql;
      od2-workers --> od2-solr;
      od2-workers --> od2-blazegraph;
      od2-workers --> od2-memcache;
      od2-workers --> CVM;

      od2-workers-migrator --> od2-redis;
      od2-workers-migrator --> od2-pgsql;
      od2-workers-migrator --> od2-solr;
      od2-workers-migrator --> od2-blazegraph;
      od2-workers-migrator --> od2-memcache;
      od2-workers-migrator --> CVM;

      od2-fcrepo --> od2-fcrepo-mysql;
```

I'm planning to take the redirects that happen at the `od1/nginx-proxy` level right now up to the BRPX level. This will return the redirects a lot more quickly to the user, and cut down on a lot of unnecessary traffic from BRPX into the cluster only to trigger a redirect that restarts the whole proxy chain over again.

We could get a similar effect with more complex Ingress rules, but let's not add more complexity than we need to. Anything beyond simple regex drag and drop of URL values like PIDs from one place to another in the URL require a lot more wrangling. Handling them at the `Ingress` level also forces the requests to all at least get proxied down to the Ingress Controllers.

The only drawback to handling the redirects at the BRPX level right now is the lack of visibility of the rules when debugging problems. Building a simple system to pull the latest versions of the files from `git` with a webhook on merges that change them, or even just pulling the current version on a schedule or some other mechanism should alleviate that.

**Comment by decimalator** [comment]
Redirects working even better. 

I was able to convert our rewrite map for OD1 so it's loadable in the BRPX proxy config for OD2. BRPX will automatically redirect:

- ContentDM Work URIs redirect to OD1 Work URIs
- ContentDM Set URIs redirect to OD2 Collections
- OD1 Work URIs (including CDM->OD1) redirect to OD2 Work URIs
- OD1 Set URIs redirect to OD2 Collections
- OD1 Works within a Set redirect to the OD2 Work
- OD1 downloads URIs redirect to OD2 downloads URIs
