### ISSUE TITLE
Add 'Local Collection Name' to facets available on search results pages

### ISSUE THREAD

**Issue by petersec** [OregonDigital/OD2#2804]
### Descriptive summary

SCARC staff have requested that the Local Collection Name facet be made available on search results pages. The two primary OSU history-focused collections in Oregon Digital - [Historical Images of Oregon State University](https://oregondigital.org/collections/osu-historical-images?locale=en) and [Historical Publications of Oregon State University](https://oregondigital.org/collections/osu-historical-publications?locale=en) - are both comprised of materials digitized out of many of SCARC's archival collections. As a component of daily work, it is important for SCARC staff to have the ability to narrow down search results within these two OD collections to aggregate content digitized out of specific local collections. Presently, the only spot where Local Collection Name is available is on the landing page for the two OSU history-focused collections noted above. Adding this functionality will also provide feature parity with OD1.

### Expected behavior

After conducting a search, I expect to see Local Collection Name as a faceting option available to me on the search results page. Upon selecting this facet, a roster of local collection names will appear as links. Selecting one of these links will allow me to aggregate all content digitized out of a specific local collection that was relevant to my original search and pulled into my search results.

**Comment by lamtu1** [comment]
@CGillen From what I understand from this is the ticket is asking us rather than having the `Local Collection Name` (that we have listed in the above statement) on the homepage. We wanted to included in the search filter option facet like shown in the picture below correct?

This mean that we wanted to have a section called `Local Collection` that has the two links to the [Historical Images of Oregon State University](https://oregondigital.org/collections/osu-historical-images?locale=en) and [Historical Publications of Oregon State University](https://oregondigital.org/collections/osu-historical-publications?locale=en). When click on it, the search will filter out those two contents and find if the file have any matches with the keyword search.

<img width="1164" alt="Screenshot 2023-07-12 at 1 09 07 PM" src="https://github.com/OregonDigital/OD2/assets/111306182/1a3ec845-940a-49c4-8b39-701775a682d3">

**Comment by petersec** [comment]
@lamtu1 @CGillen SCARC is requesting that Local Collection Name be added as a facet for all search results in the same manner as Copyright, Format, Media, etc. In other words, for all searches within OD2, Local Collection Name would be a facet available to users no matter their search terms or the collections that the search is hitting. SCARC will frequently use this for faceting within the Historical Images of OSU and Historical Publications of OSU set, but the facet should not be tied to those two sets in any specific way. Instead, it should be deployed for all content in Oregon Digital.

In terms of arrangement, it might make sense to add the facet directly beneath Collection.

**Comment by lamtu1** [comment]
@petersec This is what I got out of it and feel free to tell me if it is what you are looking for:

So under the `Collection` facet that we already have, we add in another facet directly underneath it called `Local Collection` as shown below in the image.

<img width="1147" alt="Visual" src="https://github.com/OregonDigital/OD2/assets/111306182/409f2bdd-bb9d-40c1-8aa0-625ade9b8df0">

From there, when we click on the `Local Collection`, it will expand out that there might be search result in either the `Historical Images` or the `Historical Publications` as shown below.

<img width="437" alt="Screenshot 2023-07-13 at 9 22 22 AM" src="https://github.com/OregonDigital/OD2/assets/111306182/4d3fd6b3-5fc3-4f17-a792-7f90f94f3591">

**Comment by CGillen** [comment]
Closed by #2883

**Comment by shieldsb** [comment]
The new facet is there and functions, but probably needs to have the "more" button function like other facets to keep the list from being so long.  
Here is an example: 
![image](https://github.com/OregonDigital/OD2/assets/53542788/35dc314e-4aa5-460c-9c83-076a7cfe9d99)

Current listing: 
![image](https://github.com/OregonDigital/OD2/assets/53542788/47f1935a-188f-49ed-8018-e379a8705bb5)

The other facets also allow for A-Z and Numerical sorting.

**Comment by shieldsb** [comment]
QA pass
