### ISSUE TITLE
bulkrax exporter isn't scaling well

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#2926]
### Descriptive summary

There is an export that has been running for almost a week; it is probably the largest anyone has launched, it has 27k+ items to export. The exporter job launches a child job for every item, but these child jobs run inline, so there is only one worker thread that is doing all this work. At first it appeared that we could potentially get a performance bump by enqueuing those child jobs, but the jobs only take about .5 seconds, so even though there are 27k+ of them, it still shouldn't have taken more than a few hours to get through it. Investigate creating another job that encapsulates both the child job and more of the associated work that is being iterated over, and make this new job enqueuable?

### Related work

Link to related tickets or prior related work here.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by lsat12357** [comment]
wickr also suggested that perhaps just getting the remaining upgrades done would help

**Comment by lsat12357** [comment]
QA instructions.
1. I need to set values for large_export_size and batch_size. Once that's done,
2. tester exports something that will trigger the large_export_size, eg:
3. also export something smaller than large_export_size to confirm normal exports still work.

**Comment by wickr** [comment]
QA Pass.

On staging I configured and set `BULKRAX_LARGE_EXPORT` to 500 and `BULKRAX_BATCH_EXPORT` to 100 since the staging collection sizes aren't as big.

Large export:
https://staging.oregondigital.org/exporters/45?locale=en#work-entries
More than 500 works, 1238 total entries with filesets.
I saw 13 total jobs, of OregonDigital::ExportBatchJob, running for about 20 minutes.
There were 9 reported errors but I still got two large zip downloads.

Small export:
https://staging.oregondigital.org/exporters/46?locale=en#work-entries
39 works, 79 total entries. Used Bulkrax::ExporterJob
Download successful.
