### ISSUE TITLE
All Information Based on Derivative Generation Here

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#30]
### Descriptive summary

This ticket is a nexus for information about the derivative generation process. Fill out as descriptive of information as possible about the decisions made about how this will be working. It can be an epic ticket that we can breakdown in the future.

### Steps to reproduce the behavior

1. Do this
2. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by jechols** [comment]
@vantuyls I am not sure what this ticket would need from me at this point.  We've communicated the pros and cons of various options in Google docs and in meetings, but I'm not sure it would be a good use of anybody's time to be copying huge documents into github issues.

I think what I'm getting at here is this: what is the goal of this ticket?  What specific information is being requested?  I can certainly take an hour or two to add everything I've discussed or researched about derivatives, but I don't believe that will translate into actionable items, and I feel it would be a waste of my time.

Are we looking for programming tasks to be added here?  If so, we don't have any yet.  Are we looking to present our findings to stakeholders?  If so, I think meetings and the existing documentation are going to serve us better.  Are we looking for a place to put all documentation links?  If so, I think the wiki would be a better choice, because issues eventually get closed or lost in the clutter.

**Comment by revgum** [comment]
@vantuyls @jechols Probably this document, the cost analysis for derivative generation https://docs.google.com/document/d/1NBJ-JhPGjTK2hzYGwepRuXz_QMofTx6h6bbazuIvFwI/edit

**Comment by straleyb** [comment]
@jechols I think this would be a good place to start getting info together for actionable items. 

Can we include a step by step guide on how this will all connect to SA? 
What would be a good way to pull them from the RAIS server into the application? 
How have you done it previously?
What would those URLs look like? 

Id like this ticket to be a place where we can start building out tickets with actionable items to get this functionality into SA, wether it is server related setup and configuration, or integration into SA. That would be extremely useful here.

**Comment by jechols** [comment]
Lemme try to answer some of that.

As I don't know SA pretty much at all, I can't directly speak to it, but RAIS is a general-use IIIF Image server.  As long as you plug in a IIIF-compliant client (like OpenSeadragon), it "just works".

The magic is all in the IIIF Image manifest files, e.g., https://oregonnews.uoregon.edu/images/iiif/batch_hoodrivercountylibrarydistrict_golden_ver01%2Fdata%2F2003260222%2F00000000503%2F1899110801%2F0373.jp2/info.json

That is a request which says "give me all your IIIF details."  Everything after "/iiif/" and before "info.json" is the IIIF identifier.  In this case, it's a literal (relative) path to a JP2 file on disk.  RAIS is configured to look in some root directory, then parses that IIIF ID as a path relative to its root directory.  When images are on local disk (or network mounted), it's trivial to have RAIS serve them.

First, and importantly, RAIS doesn't need to talk to the app in any way.  In fact, it would be a bad idea for a IIIF server to intimately connect to a single app, because then the third "I", "Interoperability", goes out the window.  The **app** is responsible for talking to RAIS.  Example:
- It knows that RAIS can be reached at a particular URL, e.g., `https://rais.foo.edu/iiif`
- It knows where assets derivatives live, e.g., for `oregondigital:xyzzy`, the JP2 is stored at `/var/local/images/jp2s/x/y/oregondigital_xyzzy.jp2` or something
- It knows RAIS's root is `/var/local/images/jp2s`
- It encodes the remainder of the path to figure out the IIIF ID: `x%2Fy%2foregondigital_xyzzy.jp2`
- The app then uses the OpenSeadragon JS to request the info file at `https://foo.edu/iiif/x%2Fy%2foregondigital_xyzzy.jp2/info.json`.  OpenSeadragon does the rest.

It doesn't matter if you use RAIS, Cantaloupe, RIIIF, or any other IIIF image server - other than setting up the server in the first place, the above steps are pretty much the same.

**Comment by jechols** [comment]
Derivative generation thoughts from PR #141:

- Kakadu may not be sufficient since we probably want a JP2 for every image just for consistency.
  - It would be especially painful if we found something like a 50-megapixel PNG that RAIS ended up having to process.  RAIS *can* do this, but it's a lot more RAM and disk I/O than a tiled, multi-res JP2.
  - We could build a "X to TIFF" processor that happens prior to the JP2 processor, but it wouldn't be very efficient compared to just having a single processor that does it all.
- I'll create a ticket to build a Hyrax JP2 processor that uses GraphicsMagick, since that'll handle all file types.  I'll shoot for a smart processor based on my research in https://github.com/uoregon-libraries/rais-image-server/wiki/How-To-Encode-JP2s
- I'm of the opinion that we don't need full-size images if we have a high-quality JP2 for all images.  The value of a 100-megapixel JPEG, for instance, seems iffy.  And for other use-cases, a "medium" image is probably fine.
- Semi-related: I don't think we want to be storing any binary assets directly in Fedora.  The costs would be quite a bit higher than storing the bitstreams in S3.  S3-IA is something like 1/5th the cost of EBS, and 1/20th the cost of EFS.

**Comment by revgum** [comment]
See #145

**Comment by jsimic** [comment]
POSM reviewed. Closed.
