### ISSUE TITLE
Share Tab form is broken. 

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#3074]
### Descriptive summary
It looks like the Share tab is broken. A user cannot add either a group nor a user to the list of shared with groups/users. A user also cannot delete a shared with user.

### Expected behavior

Shared with form works.

**Comment by lamtu1** [comment]
@straleyb or @CGillen As I tested more, when it comes to `Collection Sharing` things are working, and when `user or group` are added with `Manager, depositor, viewer`, it doesn't show a preview that you added but if you hit the `Save` button and once the page refresh, it does display and store value in there.

For the `Work Sharing`, value does appear when click add, but once it is save, it doesn't display for some `group or user` due to this code I found on hyrax:
```
    # Fixed set of users & groups to exclude from "editable" section of display
    def exclude_from_display
      [::Ability.public_group_name, ::Ability.registered_group_name, ::Ability.admin_group_name, @depositor]
    end
```

I was wondering do we want to display and override this anyway in the work? (Because the data does save in form for work) and do we want to display a preview what being added into the collection knowing what has being add in?

**Comment by lamtu1** [comment]
Hi @straleyb, I was just wondering that the `work form` is the only one that is broken right? I tested `collection sharing as well` and it went through fine and did retest on `work sharing` that it is broken. I just wanted to double check in that's all.

**Comment by shieldsb** [comment]
QA pass.
