### ISSUE TITLE
Certain complex objects migrated from OD1 are unable to load manifest in OD2

### ISSUE THREAD

**Issue by petersec** [OregonDigital/OD2#3076]
### Descriptive summary

A series of complex objects originally created in OD1 and migrated to OD2 are returning an 'Unable to load manifest' error toast, when one attempts to access them. All of these objects are from the Benton County Aerial Set within the [Historical Aerial Photographs of the Mid-Willamette Valley](https://oregondigital.org/collections/aerial-photos-mid-willamette?locale=en) OD collection.

Specific objects that are exhibiting this behavior are as follows (checked means fixed):

- [x] [Benton County Aerial Set, Section 1, 1956](https://oregondigital.org/concern/images/2v23vt982)
- [x] [Benton County Aerial Set, Section 3, 1956](https://oregondigital.org/concern/images/6w924c27k)
- [x] [Benton County Aerial Set, Section 4, 1956](https://oregondigital.org/concern/images/0v8381201)
- [x] [Benton County Aerial Set, Section 1, 1963](https://oregondigital.org/concern/images/xk81jk88g)
- [x] [Benton County Aerial Set, Section 3, 1963](https://oregondigital.org/concern/images/76537177m)
- [x] [Benton County Aerial Set, Section 4, 1963](https://oregondigital.org/concern/images/n583xv401)
- [x] [Benton County Aerial Set, Section 1, 1970](https://oregondigital.org/concern/images/4q77fr85c)
- [x] [Benton County Aerial Set, Section 1, 1978](https://oregondigital.org/concern/images/3484zh37b)
- [x] [Benton County Aerial Set, Section 2, 1978](https://oregondigital.org/concern/images/37720d33m)
- [x] [Benton County Aerial Set, Section 4, 1978](https://oregondigital.org/concern/images/tb09j622s)

### Expected behavior

Upon selection, objects will open and content will display within Universal Viewer.

### Accessibility Concerns

None

**Comment by lsat12357** [comment]
Looked at this during migration mtg; the first child object was originally the parent on OD1, and retained all of the children; we speculated that this was causing a problem with the parent's manifest, so Ryan cleared out the first child's ordered_members and members, reattached the correct file_set and the parent is now loading again; additionally the first child is now correctly displaying its fileset instead of its siblings. There are potentially other problems lurking, but as this seems to have fixed 6w924c27k, Ryan will go ahead and see if the other compounds listed above are facing the same problem.

**Comment by wickr** [comment]
Confirmed that for each one, the mosaic child work still had all of the other child relationships attached, so removing those and re-adding the mosaic image FileSet resolved the parent loading for each one.

QA could be just double checking the manifests load.

**Comment by KevinJonesMeta** [comment]
QA Pass.
