### ISSUE TITLE
Configure, setup, install, and code for OAI endpoint

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#38]
### Descriptive summary

OD provides its works and metadata to other groups that harvest the data using an OAI-PMH Harvester. 

Current OD OAI endpoint is: https://oregondigital.org/oai
Example result for a set/collection is: https://oregondigital.org/oai?verb=ListRecords&metadataPrefix=oai_qdc&set=oregondigital:illustrated-booklets

OD Wiki page, more details and known harvesters: https://github.com/OregonDigital/oregondigital/wiki/OAI-Documentation

https://github.com/projectblacklight/blacklight_oai_provider

### Expected behavior

* OAI endpoint works
* oai_dc and oai_qdc formats are supported
* OAI sets are configured, likely corresponding to AdminSets

### Related work

Link to related tickets or prior related work here.

**Comment by luisgreg99** [comment]
Related Work in Scholars Archive:
https://github.com/osulp/Scholars-Archive/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+oai

**Comment by wickr** [comment]
I revised the Descriptive summary and Expected behavior sections.

**Comment by wickr** [comment]
QA fail

Endpoint: https://prod.oregondigital.org/catalog/oai

`prod` should not be included in repositoryIdentifier
see https://oregondigital.org/oai?verb=Identify

ListRecords shows URIs in response for controlled fields instead of labels
https://prod.oregondigital.org/catalog/oai?verb=ListRecords&metadataPrefix=oai_dc


ListSets is not working: noSetHierarchy
https://prod.oregondigital.org/catalog/oai?verb=ListSets
AdminSets are not granular enough.
We will create a new Collection Type, called 'OAI Set' that will be a set of collections where works can be only in one, and those are what gets made available in OAI. This is analogous to `primarySet` in OD1. This OAI Set does not need to be visible to the public, but should be viewable for editors and admins. I made the type not be 'discoverable' but we may have to tweak some views.
I've made this Collection Type on staging and prod but no collections under it yet. We'll work to get some of them populated.

**Comment by wickr** [comment]
This OAI Set is made and has 5 items, so should be good to go for testing the OAI ListSets config.
https://staging.oregondigital.org/dashboard/collections/textile-and-apparel_oai?locale=en

**Comment by wickr** [comment]
QA pass.
Repository URL changed: https://staging.oregondigital.org/catalog/oai?verb=Identify

Labels showing instead of URIs in records: https://staging.oregondigital.org/catalog/oai?verb=ListRecords&metadataPrefix=oai_dc

ListSets is using OAI Sets (I added another one, ocfrp, with 5 records assigned): https://staging.oregondigital.org/catalog/oai?verb=ListSets
