### ISSUE TITLE
Notification for workflows

### ISSUE THREAD

**Issue by vantuyls** [OregonDigital/OD2#443]
### Descriptive summary

When a work enters a workflow, notification should be sent to those assigned to the workflow step for the admin set. Message:

The work <Title> (<link>) has been uploaded and is ready for your review.

**Comment by CGillen** [comment]
This behavior already happens with the message:
`<Title> (<ID as link>) was deposited by <Depositor email> and is awaiting approval`

The depositor and all users with the "approving" workflow role get this message as an in-app and email notification.
The original intent of this issue was to get the functionality working and change the contents later, so I will move this to QA. #451 shows how we can change the message.

**Comment by vantuyls** [comment]
QA Pass - received message in system upon deposit
