### ISSUE TITLE
workType cleanup

### ISSUE THREAD

**Issue by carakey** [OregonDigital/OD2#472]
### Descriptive summary

Add AAT URIs to items with uncontrolled or missing workType.

Have spreadsheets for:
- [x] SCARC Collections -- 3,408 items
- [x] Non-SCARC Collections -- 10,821 items

**Comment by carakey** [comment]
Spreadsheets of new URIs complete. Scripted batch changes pending.

**Comment by wickr** [comment]
Batch changes complete.

Some items had existing values. Most were string values for the URIs being added, or otherwise duplicates. Nearly all were deleted (marked with 'x'). 

#### Non-SCARC items - existing values ####

##### Deleted #####
x oregondigital:df70gc19f: http://id.loc.gov/vocabulary/graphicMaterials/tgm012489  # Color photographs
x oregondigital:m613mx784: http://id.loc.gov/vocabulary/graphicMaterials/tgm004499  # Gelatin silver prints
x oregondigital:df709g748: Combine painting
x oregondigital:df709g60x: Combine painting
x oregondigital:fx71bc12z: http://id.loc.gov/authorities/subjects/sh85032905  # Corporate minutes
x oregondigital:df709g66k: Combine painting
x oregondigital:df709g75j: Combine painting
x oregondigital:df709g659: Combine painting
x oregondigital:df709g641: Combine painting
x oregondigital:df709g705: Combine painting


#### SCARC items - existing values ####

##### Thought Fine to Keep #####
? oregondigital:fx71b731b: http://vocab.getty.edu/aat/300128359  # Color photographs
? oregondigital:fx71b732m: http://vocab.getty.edu/aat/300128359
? oregondigital:fx71b7345: http://vocab.getty.edu/aat/300128359
? oregondigital:fx71b735f: http://vocab.getty.edu/aat/300128359
? oregondigital:df70cb09g: http://vocab.getty.edu/aat/300127104  # photographic prints

##### Unsure #####
? oregondigital:fx71bx05v: http://vocab.getty.edu/aat/300265164  # boudoir photographs
? oregondigital:fx71bw94j: http://id.loc.gov/vocabulary/graphicMaterials/tgm009643  # Silver printing-out paper prints

##### Deleted #####

x oregondigital:df70c7613: portrait photographs
x oregondigital:df70c8512: published photographs
x oregondigital:df70bz32t: negatives (photographic)
x oregondigital:df70d167p: published photographs
x oregondigital:df70d168z: published photographs
x oregondigital:df70d1654: published photographs
x oregondigital:df70bz308: negatives (photographic)
x oregondigital:gb19f6239: Glass copy negatives
x oregondigital:cf95jb826: Glass
x oregondigital:qn59q445k: Glass copy negatives
x oregondigital:cn69m451z: Glass copy negatives
x oregondigital:df70ck10p: negatives (photographic)
x oregondigital:df70c592p: http://id.loc.gov/vocabulary/graphicMaterials/tgm007089
x oregondigital:df70ch56w: negatives (photographic)
x oregondigital:df70c4054: negatives (photographic)
x oregondigital:df70c404v: negatives (photographic)
x oregondigital:fx719m49w: http://id.loc.gov/vocabulary/graphicMaterials/tgm007089  # Nitrate negatives
x oregondigital:df70d775m: http://id.loc.gov/vocabulary/graphicMaterials/tgm007089
x oregondigital:df70d7707: http://id.loc.gov/vocabulary/graphicMaterials/tgm007089
x oregondigital:fx71bj67k: http://id.loc.gov/vocabulary/graphicMaterials/tgm007089
x oregondigital:df70cq94j: negatives (photographic)
x oregondigital:df70cq95t: negatives (photographic)
x oregondigital:df70c443j: negatives (photographic)
x oregondigital:df70c0059: negatives (photographic)
x oregondigital:df70cm32x: negatives (photographic)
x oregondigital:df70cm336: negatives (photographic)
x oregondigital:df70cm34g: negatives (photographic)
x oregondigital:df70cm247: negatives (photographic)
x oregondigital:df70ch96v: negatives (photographic)
x oregondigital:df70cj695: negatives (photographic)
x oregondigital:df70cc09p: negatives (photographic)
x oregondigital:df70cc10f: negatives (photographic)
x oregondigital:df70cc11q: negatives (photographic)
x oregondigital:df70cc120: negatives (photographic)
x oregondigital:df70cx820: negatives (photographic)
x oregondigital:df70ch507: negatives (photographic)
x oregondigital:df70cj91p: negatives (photographic)
x oregondigital:df70cj70x: negatives (photographic)
x oregondigital:fx71bx01r: http://id.loc.gov/vocabulary/graphicMaterials/tgm002296  # Collodion printing-out paper prints
x oregondigital:df70cb89d: http://id.loc.gov/vocabulary/graphicMaterials/tgm007089  # Nitrate negatives
x oregondigital:df70cc95r: negatives (photographic)
x oregondigital:df70c158j: negatives (photographic)
x oregondigital:df70c244d: negatives (photographic)
x oregondigital:df70c246z: negatives (photographic)
x oregondigital:df70c245p: negatives (photographic)
x oregondigital:df70c241k: negatives (photographic)
x oregondigital:df70c2409: negatives (photographic)
x oregondigital:df70c253c: negatives (photographic)
x oregondigital:df70c2477: negatives (photographic)
x oregondigital:df70c248h: negatives (photographic)
x oregondigital:df70cd02z: http://vocab.getty.edu/aat/300127173  # negatives (photographs)
x oregondigital:df70cd037: http://vocab.getty.edu/aat/300127173
x oregondigital:df70cs92d: negatives (photographic)
x oregondigital:df70cs93p: negatives (photographic)
x oregondigital:df70cs94z: negatives (photographic)
x oregondigital:df70c118k: http://id.loc.gov/vocabulary/graphicMaterials/tgm007089  # Nitrate negatives
x oregondigital:df70c453s: negatives (photographic)
x oregondigital:df70c452h: negatives (photographic)
x oregondigital:df70c421h: negatives (photographic)
x oregondigital:df70c422s: negatives (photographic)
x oregondigital:df70hs48j: windows media audio
x oregondigital:df70hs49t: windows media audio
x oregondigital:df70hs50k: windows media audio
x oregondigital:df70hs51v: windows media audio
x oregondigital:df70hs524: windows media audio
x oregondigital:df70hs346: windows media audio
x oregondigital:00000029z: Nitrate negatives
x oregondigital:5712m6834: Nitrate negatives
x oregondigital:j6731409k: Nitrate negatives
x oregondigital:jq085k35k: Nitrate negatives
x oregondigital:df70cz70d: negatives (photographic) (photographic)
x oregondigital:ww72bb81p: Nitrate negatives
x oregondigital:df70c694f: http://id.loc.gov/vocabulary/graphicMaterials/tgm007089  # Nitrate negatives
x oregondigital:df70d6655: http://id.loc.gov/vocabulary/graphicMaterials/tgm009620  # Signs (Notices)
x oregondigital:df70d667q: published photographs
x oregondigital:bv73c070s: Magazine covers
x oregondigital:df70cv712: http://id.loc.gov/vocabulary/graphicMaterials/tgm001202  # Book covers
x oregondigital:df719s438: http://id.loc.gov/vocabulary/graphicMaterials/gm001202  # invalid, but Book covers
x oregondigital:df70d6808: http://id.loc.gov/vocabulary/graphicMaterials/tgm007089  # Nitrate negatives
x oregondigital:df70d681j: http://id.loc.gov/vocabulary/graphicMaterials/tgm007089
x oregondigital:df70d682t: http://id.loc.gov/vocabulary/graphicMaterials/tgm007089
x oregondigital:df66tv487: http://id.loc.gov/vocabulary/graphicMaterials/tgm009620
x oregondigital:df66tv55n: http://id.loc.gov/vocabulary/graphicMaterials/tgm009620

**Comment by wickr** [comment]
With the review and cleanup of the existing worktypes done, this is now entirely complete.
