### ISSUE TITLE
UO login works but persists - will not logout

### ISSUE THREAD

**Issue by raybrarian** [OregonDigital/OD2#475]
### Descriptive summary

After successful UO login, cannot log back out. Cookie issue? Cached credentials?

### Expected behavior
Can use logout link to exit session.

### Related work

#173 is related

**Comment by raybrarian** [comment]
Update: I get the toast message "Signed out successfully" in Chrome/Firefox, then when I click on the UO Login link (even after closing the tab), I get the "Successfully authenticated from saml account" toast without going through shib. When I logout, I get the "Signed out successfully" toast, but can immediately get logged back in without a reauth pass through shib. Expected behavior is that I would be forced to reauthenticate, true?

**Comment by straleyb** [comment]
@CGillen Is this still an error?

**Comment by CGillen** [comment]
@raybrarian This is intended/unfixable behavior. Our institutional shibboleth does not have session logout configured (I'm unsure if this is an option in shib). This means once you authenticate for an app through UO Shib, you may signout from that application (if the application supports it), but attempting to sign in through Shib again will automatically log you back into the previous account, until you close the browser or otherwise expire your session/cache.
