### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#53]
### Descriptive summary

Analytics is a big topic of discussion. Hyrax has some analytics and we will need to set up a google account and configure it in the system. Also, we may need to talk about porting over any analytics from the old system to the new system.

Furthermore, we will need to work on enhancing the analytics. This ticket is for discussion about the analytics. Are we going to work on analytics? Is someone else? What are the requirements?

**Comment by vantuyls** [comment]
Analytics overhaul is on the current roadmap for hyrax. i suspect we'll get to this, though we may want to consider whether OD has resources to put towards this effort. 

I would also argue for taking hyrax analytics (after overhaul) as-is and consider any additional changes to analytics as feature enhancement, rather than MVP.

**Comment by straleyb** [comment]
Notch 8 Work.
