### ISSUE TITLE
Generate seed data for OD2

### ISSUE THREAD

**Issue by vantuyls** [OregonDigital/OD2#57]
### Descriptive summary

We need to generate a seed dataset for OD2. This will allow us to better QA UI changes and allow for building catalog controller etc.

@jsimic @petersec @wickr can you define a seed dataset for us to start with?

**Comment by wickr** [comment]
Seed Data pids list is here: https://docs.google.com/spreadsheets/d/1czaBQQrADv7WbyNgjk4KYyikpkDvutCsOTRjcLLS2MM/edit?usp=sharing
(not including for now the restricted Texts and Data files)

**Comment by wickr** [comment]
@lsat12357 generated Bags from the Seed Data pid list, by 'group'. Those files are now up on Box for download as needed: https://oregonstate.box.com/s/jw4767z4w1sntsch35r0wjvnah2ptldy

**Comment by wickr** [comment]
QA: I don't think more is needed. OSU ETS members should have full access to Box folder if anything ever needs updating. URL above is public so everyone else on team can download some or all of the Bags. Box has an option to Download everything but also has a 15GB limit for all accounts, so that won't work. You can select multiple files/folders still, as long as the total doesn't go over 15GB.
