### ISSUE TITLE
2 separate Type facets showing up

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#579]
### Descriptive summary

There's currently 2 separate Type facets showing up. I believe this is because old index values are hanging around, and we need to reindex all works.

http://staging.oregondigital.org/catalog?f%5Bhuman_readable_type_sim%5D%5B%5D=Video&locale=en&q=&search_field=all_fields
![image](https://user-images.githubusercontent.com/2293544/59728847-9cc75b00-91f0-11e9-991d-a240f56840e9.png)

### Expected behavior

Only 1 Type facet

**Comment by vantuyls** [comment]
qa fail - still seeing two Type facets on search results. 

replicate: 
1) go to OD staging
2) select the search button (to return everything)
3) one Type facet at the top, one near the bottom

**Comment by raybrarian** [comment]
QA still fails - two Type facets still show per steps above.

**Comment by raybrarian** [comment]
Now showing three separate type facet labels:
- Object Type
![image](https://user-images.githubusercontent.com/4460510/61827771-2edb0880-ae1a-11e9-9385-9eb984578e2e.png)

- Work Type
![image](https://user-images.githubusercontent.com/4460510/61827803-3f8b7e80-ae1a-11e9-8e02-1967941f7091.png)

- Type
![image](https://user-images.githubusercontent.com/4460510/61827837-54681200-ae1a-11e9-8ad8-6933fbd0a188.png)

QA pass for this specific issue - @wickr, is this the expected behavior for prod, or will some of those facets be suppressed going forward? I think Kate is setting aside time to look at staging in the POSM meeting on the 29th, so this question can wait until then - just wanted to give you a heads-up!
