### ISSUE TITLE
Work Show Page: Add 'Add to My Shelf' button

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#604]
### Descriptive summary

Add new "Add to My Shelf" button to top right of work show page.

Wireframe mockup: https://www.lucidchart.com/documents/edit/944f6fd3-53b5-466b-b49f-f0788ada80aa/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

'Add to My Shelf' button in the top right of work show page makes it easy for users to to add works they view.

**Comment by raybrarian** [comment]
Button shows for logged-in users only - I *think* this is meant to show for unauthenticated users as well (but should send them to auth first, then pass them to add to MyShelf). 

Hmm, if that's the case, then I think this needs an auth chooser landing page - the page I argued against making. :/ @kmthorn, @petersec  - was that your understanding that this button would show for everyone, and authenticated or not?

**Comment by petersec** [comment]
I think our discussion of this issue got bogged down a bit in the different permissions issues that we're facing. It makes sense to me that we would mostly want MyShelf to show up for everyone all of the time, so that it's obvious that MyShelf is a thing. The logic goes that if someone sees that MyShelf exists and wants to add an item, then they get moved to the auth chooser landing page if they're not already logged in, and away they go. I think this will mostly work out fine. 

That said, there might be instances where someone is looking at restricted UO content on campus and finds that they don't have the proper (or equivalent) permissions once they're off campus. (or other problems arising from IP restricted content - @kmthorn @jsimic have a much more complete understanding of these potential scenarios than do I) My memory is that we were leery of displaying a MyShelf option to a user who may not actually be able to add it their shelf, since that would seem anger-making.

**Comment by jsimic** [comment]
Kate and I updated the wireframes to reflect the discussion from last POSM regarding unauthenticated users (see https://drive.google.com/open?id=1-bqPxT3Dy5nJDbbGcltny-kto_Slq683 ) with the assumption that the MyShelf button would be visible on work show pages and search results at all times and when clicked would prompt the user to login. Anything IP restricted is not seen by an unauthorized user, so they never have the option of adding it. The difficulty was if an authorized user saved a restricted item to a MyShelf folder and then tried to share it out to unauthorized users. In which case, anything with an IP restriction will require a warning that the item is restricted and may not be sharable at the time it is saved to MyShelf (see https://drive.google.com/open?id=1fBG0zJzDAaf4m-xs2MVDWvNYNEirY8wP ). An unauthorized user would simply not see the restricted item in the shared MyShelf folder.

**Comment by raybrarian** [comment]
Thanks, @jsimic and @petersec! I'll keep an eye on this ticket for the next steps of development on MyShelf, and will make sure the linked wireframes/drawings get associated with that next phase.

@CGillen - so the "Add to My Shelf" button should show for all users for all items (except those which are restricted). Is that possible to do? If we can do that, then POSM can get additional tickets written up for the expected functionality Julia is identifying above.

**Comment by CGillen** [comment]
Yup, since the button doesn't do anything now it can show up whenever.
I doubt we'll need a warning about share-ability when adding restricted items to MyShelf. A user's shelf shouldn't have any share functionality, as far as I'm concerned. That's what direct URLs and the copy share link button is for.

**Comment by jsimic** [comment]
@CGillen @raybrarian The Add to MyShelf button should show for every work. If it's a restricted work, unauthorized users don't even see it, and thus can't add it to MyShelf. 

MyShelf sharing is for sharing a curated group of works. Vital for instructors. See Artstor.

**Comment by raybrarian** [comment]
QA pass - add to my shelf shows for all items, also shows for institutionally restricted item.
