### ISSUE TITLE
Work Show Page: In Right column, add new "Can I Use?" section with license/rights

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#611]
### Descriptive summary

In the right column, add new "Can I Use?" section. Display the license icon, title, and external link. If there is no license value, fall back to the Rights Statement value with icon, title and external link. But if there's both, only show License.

Wireframe mockup: https://www.lucidchart.com/documents/edit/944f6fd3-53b5-466b-b49f-f0788ada80aa/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

Can I Use? section highlights license or rights information for the work.

**Comment by raybrarian** [comment]
@petersec @kmthorn @cgillen - it's my understanding that we aren't displaying the icons because we don't have access to fontawesome 5 (or another icon set). Is this something we need a purchase request written up for? 

One other thing - this license link opens in a new window (which can be difficult for screenreader users and others who want to use the browser's Back button). Is that the expected functionality?

**Comment by CGillen** [comment]
@raybrarian Currently, Hyrax uses a gem which has refused to upgrade from FontAwesome 4 to 5. It's the more heavily used gem of the two I'm aware of ([font-awesome-rails](https://github.com/bokmann/font-awesome-rails) vs [font-awesome-sass](https://github.com/FortAwesome/font-awesome-sass)). The problem with switching to FA5 is that it's a breaking upgrade, and tons of hard-coded hyrax non-sense would break.
So it's a technical limitation, not monetary.

Since it's an external link I would think a new window is preferred. It's also not a concise decision, it's default Hyrax. Definitely changeable, but will probably cause inconsistencies elsewhere.

**Comment by raybrarian** [comment]
@CGillen Ahhh - got it re: font awesome! So, even though modern browser users are accustomed to spawning new windows, even external links should probably not open in a new window because it can be disorienting to folks with cognitive and/or visual impairment - it's that breaking of the Back button functionality that should be avoided. 

If we feel like we need to open a new tab or window, the link text should indicate that's the case.  Techniques from WCAG 2.1 - similar techniques are in 2.0:
[Opening new tabs or windows](https://www.w3.org/WAI/WCAG21/Techniques/general/G200)
[Advanced warning of links opening in a new window](https://www.w3.org/WAI/WCAG21/Techniques/general/G201)

**Comment by raybrarian** [comment]
Fallback to rights statement is working, links still open in a new tab.

**Comment by mccallum** [comment]
I'm a big fan of inline SVG for icons above and beyond what your base offers: http://jsfiddle.net/6WAtQ/

**Comment by raybrarian** [comment]
QA pass. Rights statement no longer opens in a new tab/window.
