### ISSUE TITLE
Search Results: Gallery View: Metadata fields update

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#687]
### Descriptive summary

On Search Result, Gallery View, change the metadata fields that are displayed (below Title). 

  - Creator: show up to 3 creators, display 'and others' when more than 3
  - Date
  - Description: Truncate to 10 words, with ellipsis
  - Resource Type

Wireframe mockup, Gallery (or 'Grid') View: https://www.lucidchart.com/documents/edit/b536687b-3acd-4ac4-ad4e-638cde427a4f/0

(Information compiled by POSM group from updated wireframes)

### Expected behavior

Metadata fields shown are only Creator, Date, Description, and Resource Type.

### Related work

#683

**Comment by CGillen** [comment]
QA:
- [ ] Search results page gallery view: Creator field displays at most 3 creators + "and others"
- [ ] Search results page gallery view: Date field exists, currently displayed as "date modified"
- [ ] Search results page gallery view: Description field displays at most 10 words
- [ ] Search results page gallery view: Resource type is not displayed in metadata field, instead displayed below with a relevant icon

**Comment by raybrarian** [comment]
Three questions for @wickr here - contributors are not similarly truncated - should they be? 
![image](https://user-images.githubusercontent.com/4460510/63179824-d73b5180-c001-11e9-91dc-5b8ca1355bd6.png)

Is this the expected behavior for the description truncation when there's a new paragraph/paragraphs?

![image](https://user-images.githubusercontent.com/4460510/63179929-09e54a00-c002-11e9-94be-4aae981c509c.png)

Is it possible that there will be items without resource types, and if so, is having no default the expected behavior?

![image](https://user-images.githubusercontent.com/4460510/63180213-a0b20680-c002-11e9-9562-a2f8a8edfa0d.png)

**Comment by raybrarian** [comment]
@cgillen - I'll let Ryan W weigh in here first, but the displayed metadata fields are not currently limited to Creator, Date (Modified), Description, and Resource Type. Do you want a new ticket for that?

**Comment by CGillen** [comment]
Nope, not a new ticket. Just make me read this one in full >.<
I missed the part about limiting the displayed fields.

**Comment by wickr** [comment]
Yeah limiting the fields shown should pull out Contributor. 
For Description, the multiple fields with truncation is odd. We may want to ditch the 'and' as a separator here.
Resource Type is a required field so we should be fine expecting it to be there.

**Comment by shieldsb** [comment]
QA pass.  Located one item that does not have resource type metadata included, so there is no icon displayed.  I see the note above from Corey about it being required.
