### ISSUE TITLE
High Res Image downloads

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#760]
### Descriptive summary

Yes for all content a user can view. 
-Depositors, Collection Curators, and admin can download high res for all,
-OSU and UO can download high res for anything they can discover which means no restricted content.

**Comment by wickr** [comment]
It's not accurate that anyone who can view something can get the High Resolution files. Otherwise there'd be no access difference between High Res and Low Res. Also, we're planning on using the Access Restrictions property to set values for the specific groups that have access to high res download. The Metadata Team needs to do a bit more finalizing of exactly how this is going to work. 
I think work on this can wait until more of this is finalized. If you need to set up the ability now you could, but the specifics aren't going to be fully correct.

**Comment by CGillen** [comment]
See #759 for QA

**Comment by shieldsb** [comment]
QA pass.
