### ISSUE TITLE
Images arent being characterized/derivativeized 

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#783]
### Descriptive summary

This may have to do with some old code lingering around s3 derivative work or around the new k8s setup, but when you ingest any work with a file, the file doesn't actually get "uploaded" You can add as many files as you can as many times as you can and it wont add them.

**Comment by shieldsb** [comment]
@jechols

**Comment by jechols** [comment]
It's probably worth testing this with a variety of content types.  The bits of work I've done have been only for images and PDFs, so if those don't work, there may be some S3 problems.  On the other hand, if those *do* work, but things like MP3s don't work, it could be that I ripped something out I shouldn't have when customizing the processing for images and PDFs - in which case it's likely not related to S3 so much as the other customization done for derivative work.

If nothing works at all, it's not *probably* not what I've done, but I wouldn't rule anything out, given the lengths I've gone to customize the derivative process.  And while I can still remember what I was doing with external derivative workers, that wasn't merged.  I have no memory anymore of the work I've done otherwise -- those external workers were the majority of my last workcycle as I recall.

**Comment by shieldsb** [comment]
I've tested jpeg, PDF, mp3, xls, and none of them have successfully uploaded.

**Comment by jechols** [comment]
An image ingest works fine locally, so I'm going to have to look at the staging server to make any guesses as to what's going on

**Comment by jechols** [comment]
This should be fixed - it seems it was due to a broken configuration on our kubernetes setup (we changed things in dev but didn't change things in the k8s setup)
