### ISSUE TITLE
Have a discussion regarding how we want the review functionality to work.

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#816]
### Descriptive summary

This is a place to aggregate information based on discussions about the limitations on hyrax for reviewing and users that can review. 

The way hyrax works is, currently, when a work exists in a collection/admin_set and is under review, and then a user is added as a manager to that collection/admin_set, then that user cannot review the works that existed before their addition as a manager.

We have a few options about how to proceed, but a discussion needs to occur with service managers about what the needs are of the application vs what is feasible in hyrax.

**Comment by CGillen** [comment]
We just need to document the general use case and workflow that's being forced on us by Hyrax. Use groups instead of specific people in review workflows, that way users can come and go at any time.
There are also ways from the console to add users to a workflow after the fact. Research and document those commands here and elsewhere (wiki? gdrive?)

**Comment by CGillen** [comment]
Review queue work is going on in #1460. We'll discuss and make decisions there or other tickets
