### ISSUE TITLE
Lock down titles for roles to not be editable. 

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#840]
### Descriptive summary

We don't want titles to be altered since the system banks on the titles being specific. Remove the ability to edit titles on the roles edit page.

**Comment by raybrarian** [comment]
Appears to be QA fail - not a logged-in user and am able to edit & save role title:

![image](https://user-images.githubusercontent.com/4460510/67712005-60ff8780-f980-11e9-8f74-78e8351b1d45.png)

@straleyb - are we waiting on a deploy? If so, please move this back to in progress - otherwise I will push it back to ready. Thanks!

**Comment by CGillen** [comment]
QA: Wait until footer moves from `Oregon Digital WC3-0.0.1-20191023165215-32aab30`
- [ ] Role edit page does not display textbox or update button

**Comment by raybrarian** [comment]
QA pass.
