### ISSUE TITLE
A better reindexing solution

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/OD2#922]
### Descriptive summary
The default Solr reindexing solution `ActiveFedora::Base.reindex_everything` is slow and prone to randomly missing documents. Since reindexing is infrequent enough, we're likely to forget the process and pitfalls every time we go back to do it. It would be good to have a sure-fire rake task that does a better job not missing documents.

If there's speed improvements we can find, that's a bonus.

### Expected behavior
New rake task exists that reindexes ALL documents for Solr.

### Related work
#818 Reindex while finish this ticket on staging brought this up.
A manual reindex after Solr8 pod lost it's persistent volume also caused us to lose some documents and took 1:45:00 to reindex 31.4k documents for 9 works and 123 collections. We expected to see 300+ works after the reindex. Works were locatable ActiveFedora by pid, but not with `#all` methods.

### Accessibility Concerns
N/A

**Comment by jechols** [comment]
Working on a really crazy brute-force index tool right now.  It's ugly and slow, but it seems to be *less* brute-force than the built-in `reindex_everything` while indexing things more effectively somehow.  Still not sure how that worked out.

The tool's approach is to grab every URL Fedora offers us, read the metadata for them, and decide if any given URL represents an object we want indexed.  Most objects' children are also crawled, but we're deliberately ignoring things like permissions because that adds a *lot* of overhead to the reindex operation and permissions / access control / etc. **seem** to be reindexed when you call an asset's `update_index` method.

We should test that all child data is properly indexed when an asset is indexed, though.  If so, we can probably continue chugging away at a simpler-but-more-reliable script.

FYI my code is currently in a branch called "feature/reindex"

**Comment by jechols** [comment]
Many updates since starting this.  I'll try to summarize.

Reindexing by making one job per fedora object is not actually going to work.  It seems that some objects are tied to others in really weird ways.  But Fedora has no concept of querying by metadata fields - you can only ask for an item by its id.  However, the tightly coupled things are separate Fedora objects with no obvious tie in their ids.  Which makes it impossible to only use Fedora to figure out what's tied to what.  Some objects *must already exist in Solr* simply to index objects.

Example: Image identified by pid `3t945r08v` has discovery access for groups `public`, `admin`, `depositor`, and `curator`.  It has groups for editing as well, and even an explicit `edit_access_person` field.  These permissions, though, are stored individually in other Fedora objects.  The one that says "admins have discovery access" is at id `1b933f0c-3e2a-4a0a-ada6-25b2ad05a588/01/94/94/6a/0194946a-57a5-4535-92bf-bda920679c45`, which is a child of the access control object at id `1b933f0c-3e2a-4a0a-ada6-25b2ad05a588`.  There's a clear connection between the access control's id and the individual permissions' ids, but no connection at all to the asset's pid.  It's only when indexed into Solr that we can find it by asking "what permissions objects have an `accessTo_ssim` field with our asset's pid?".

So what does this all mean?  I think I have to build a *much* smarter (and therefore more complex) indexer.  I need to fully understand all the different Fedora objects and how they relate to an asset.  Then my reindex job can be given a *list* of ids to reindex, in the order they need to be indexed.  This would let us index a single asset and all its dependencies as a single reindex job.

So... good luck, future me!

**Comment by jechols** [comment]
Interesting twist: if you reindex an asset without its permissions already being in Solr, the stack creates *new* permissions objects entirely.  So if we can't get the reindex working the right way, we could not only blow away permissions in horrible ways, but leave all kinds of busted, orphaned data in Fedora.

**Comment by jechols** [comment]
So here's another odd twist: the data in Fedora does in fact tell us how to find all access controls objects.  I was looking for permissions specifically, but there's an access control container of sorts, and its id is referenced in the asset.  But for some reason, Hyrax won't find it if it's not in Solr.  So the problems stated above are indeed still problems, just not for the reason I thought (unlinked data).

**Comment by jechols** [comment]
Note to self: the reindex will need to also kick off fetch graph workers for all assets; this doesn't happen automatically when a work is reindexed, just on creation

**Comment by jechols** [comment]
Latest iteration of my reindexer seems to get permissions properly, but all the other tertiary bits aren't being caught: proxy objects, containers, etc.  I have no idea what they do, but I suspect they need to be indexed prior to their assets just like permissions.

**Comment by jechols** [comment]
The latest code up in `feature/reindex` seems to work.  It's ugly and has no unit tests, but locally it does seem to rebuild the index *precisely* as it was before destroying it.

**Comment by jechols** [comment]
Ready for QA.  The QA process is to actually run the reindexer, but it's expected to be slow.  It *should* only take an hour to index 1100 assets, but that's a big unknown because of how slow it is in development.

So one option is to just reindex on staging.  This is "easy", but if it takes a day to reindex, this will slow down everything staging is doing, and indexes will potentially be in a weird state of flux.  Additionally, because of the busted reindexes we've done in the past on staging, we really want to completely destroy the solr data before we start this process.

Another option is to spin up a whole separate infrastructure somehow (@DeadCatLady and @decimalator would have to address this, I think), and reindex into a totally new solr.

One potential problem we may run into is orphaned Fedora data.  With the Hyrax stack's reindexing bugs, it's likely we have permissions objects which exist in Fedora and are tied to real objects... but the assets don't know about them anymore.  This reindexer reads *everything* in Fedora.  If there's orphaned data, and I expect that there is, I don't know what ends up happening....

**Comment by CGillen** [comment]
QA:
Ran several times.

Latest run took about 3.25 hours to get through 1156 works and 120 collections. This included an unknown amount of weird access assets and totaled 40771 solr documents and the same number of ActiveFedora objects (good indicator that we got indexing correct).

This is slow but @jechols has opened and is working on #936 to investigate possible optimizations as this could be bad for us if facets need to change, new metadata is added, or Solr needs to go through an upgrade.
