### ISSUE TITLE
no space left on device error

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#925]
Occurred during migration on workers pod
2019-12-20T17:44:53.028Z pid=1 tid=ox08s7hi1 WARN: MiniMagick::Invalid: `gm identify /tmp/mini_magick20191220-1-t9zlg8.pdf` failed with error:
gm identify: An error has occurred writing to file (/tmp/mini_magick20191220-1-t9zlg8.pdf) [No space left on device].

@wickr suggested that rather than adding additional space, this might be solved by making sure the directory is cleaned out more often.

**Comment by jechols** [comment]
This won't be solved by cleaning `/tmp` - derivative processing eats a lot of space as it's happening, and it can't be cleaned up any faster.  Right now there are several gigs of data in `/tmp` and more than 90% of that is from the last few minutes.

This is a problem because the `/` mount only has 10 gigs and that's shared with OS files and basically anything not explicitly set up as external storage.  In a best-case scenario, when `/tmp` is empty, we seem to have roughly 5 gigs.  Processing a PDF results in one BMP per PDF page, and each BMP is in the range of 25 megs (from the data I'm seeing right now).  That means that it only takes forty pages being processed at once to burn one gig.  A large PDF can have ten times that many pages.

It's possible we could rewrite the PDF processing to be 100% custom code (i.e., not using abstractions like MiniMagick) to only process pages one at a time and immediately clean up after themselves.  This unquestionably would save us on storage space, but it will also complicate the codebase, and it's not something we can do right this second to get past this problem.  It's also a very short-term solution, because 5 gigs of temp space is incredibly easy to eat up when we have a lot happening, even if we make PDFs better.  Huge images will pose a problem, then there's videos, audio, and who knows what other stuff needs to use `/tmp` separately from derivatives?

**Comment by jechols** [comment]
Looking at our code, I don't think we even *can* improve the PDF processing.  It's looking like it doesn't actually unravel every page at once, unless MiniMagick is doing something really weird (which wouldn't make much sense since that is supposed to just wrap command-line calls to `gm`).

I think we're running out of space because we start with 20 workers, and they're all generating mounds of tempfile garbage, which, combined, runs us out of space.  The jobs crash in a variety of ways, and sometimes the temp files aren't cleaned up, leading to less and less available temp space until even a single job running by itself can't succeed.

**Comment by jechols** [comment]
Okay, now I think I have a better idea what's up.

- Ruby's Tempfile class automatically deletes the tempfile *after garbage collection is done*.  Brilliant.  This makes devs think they shouldn't worry about deleting files.
- MiniMagick uses Ruby's Tempfile in the naive way
- The PDF processor runs through the PDF pages quickly
- The GC probably runs every few minutes
- 100+ pages can easily be MiniMagick-converted in the time between GC runs
- Disk fills, processes crash

So even if we only have a few PDF processes happening, it's entirely possible that they'll die if they have a lot of pages.  We don't need a ton of jobs to run into this problem; we just need a big PDF or two.

Solution?  Still not sure.  Manually process PDFs via our own shelling out to `gm`?  Fork MiniMagick?

(There's a nearly-two-year-old issue about this, so I don't think we can count on MiniMagick getting a fix: https://github.com/minimagick/minimagick/issues/447)

**Comment by jechols** [comment]
It's worth noting that since we use `MiniMagick::Tool::Convert.new do |cmd|`, I have no idea how we'd try to deal with the suggestion to use `image.destroy!` in that ticket.

**Comment by jechols** [comment]
Looking deeper into the minimagick codebase, I don't think a fork is an option.  MiniMagick does different things with its tempfile function depending on context, so there isn't really a one-size-fits-all option (we use it in multiple contexts).

Manually removing tempfiles is going to be necessary somehow, otherwise we're looking at rewriting what MiniMagick does, which in the context of PDFs won't be impossible, but certainly is nontrivial.

**Comment by decimalator** [comment]
I have attached a Kubernetes `emptyDir` volume to the workers deployment and mounted it as /tmp. There is no limit set right now, so the limit is the physical capacity of the disk on the node it is running on. Right now that's not a HUGE upgrade, but this will give us at least 50GB capacity once I finish #935

**Comment by jechols** [comment]
Forgot to mention it there, but PR #933 should help here as well

**Comment by lsat12357** [comment]
I ran two batches (one of 20 pdfs, one of 20 tiffs) concurrently on the OD2020 cluster, everything finished without errors in sidekiq

**Comment by raybrarian** [comment]
per @lsat12357, QA pass
