### ISSUE TITLE
modeshape error

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#926]
This gnarly error occurred during migration:
workers_1     | [ActiveJob] [Hyrax::Migrator::Jobs::MigrateWorkJob] [8e177ee5-da3d-45d5-bc95-eb1470be0eab] failed persisting work df70b7651, STATUS: 500 org.modeshape.jcr.cache.NodeNotFoundInParentException: Cannot locate child node: 2ac12d17505d6475a61bc2-38a7-468c-9eaf-b2c8c77b8be3 within parent: 2ac12d17505d64c7f68e6c-cc6c-4a4c-98be-9e4ed7401af3

Although it says "failed persisting," my recollection is that the asset actually was persisted; i.e. I could load it using ActiveFedora::Base.find. Attempting to deal with it by deleting the asset resulted in the same error.
I believe the child node the error refers to is actually a file; so I was eventually able to fix this by running the attach files job on the asset.

Not sure why the error happens in the first place; I posted a question on the samvera slack channel, but no responses forthcoming (week before Xmas).

**Comment by luisgreg99** [comment]
I ran into this issue when migrating Fairbanks_Fine_Art_Prints_Collection. Two works df65vf79s and df65vf157 were having this issue. In addition to files, I found that workflow sipity entity (workflow states) records didn’t get created as well due to this error. I manually added the sipity entities (added branch [fix/create_sipity_entity](https://github.com/OregonDigital/OD2/compare/fix/create_sipity_entity)), to be able to approve these files.

**Comment by luisgreg99** [comment]
Found a related ticket in https://issues.redhat.com/browse/MODE-2610?_sscc=t

**Comment by luisgreg99** [comment]
Updated [fix/create_sipity_entity](https://github.com/OregonDigital/OD2/compare/fix/create_sipity_entity) branch and added `publish_work` to manually publish a private work if it is expected to be open given a pid.

**Comment by luisgreg99** [comment]
During migration meeting today, we agreed to close this ticket and move the tasks and proposed code in a wiki page https://github.com/OregonDigital/hyrax-migrator/wiki/modeshape-errors in hyrax-migrator with steps to workaround the issues.
