### ISSUE TITLE
derivatives process trying to process excel files

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2#938]
although no derivatives are required for this file, df661w36p_content.vnd.ms-excel,  MiniMagick appears to be trying to do something:
MiniMagick::Error: `gm mogrify -flatten /data/mini_magick20200108-1-1915w7j.pdf[0]` failed with error: gm mogrify: Unrecognized option (-flatten).
This is mainly just annoying, because these jobs will need to be cleared out so that sidekiq isn't repeatedly retrying them

**Comment by jechols** [comment]
It looks like this Excel issue might be due to something in core Hyrax.  Specifically, I believe core Hyrax is doing something to try and make thumbnails out of Excel files (why??), which uses PDFs somewhere for some reason, and that's not interacting well with our GraphicsMagick setup, because GraphicsMagick's `mogrify` command doesn't work the way ImageMagick does.

We may have to completely take over the processing of all Document-type files to fix this.  I hope not, though.

**Comment by raybrarian** [comment]
Migration Team will QA when collection is on Staging

**Comment by lsat12357** [comment]
This tests fine locally, but oddly, having issues on staging

**Comment by lsat12357** [comment]
Error performing CreateDerivativesJob (Job ID: b3508022-cad2-4e1b-a8bb-a194236bbcd1) from Sidekiq(default) in 1505.18ms: NameError (uninitialized constant OregonDigital::Derivatives::Document
Did you mean?  Document):
/data/app/services/oregon_digital/file_set_derivatives_service.rb:82:in `create_office_document_derivatives'
/data/app/services/oregon_digital/file_set_derivatives_service.rb:33:in `create_derivatives'
/data/app/services/hyrax/derivative_service.rb:33:in `block in create_derivatives'
/data/app/services/hyrax/derivative_service.rb:33:in `map'
/data/app/services/hyrax/derivative_service.rb:33:in `create_derivatives'

**Comment by luisgreg99** [comment]
fixed by https://github.com/OregonDigital/OD2/pull/1002

**Comment by luisgreg99** [comment]
QA Pass:
`df661w36p` was successful on staging
