### ISSUE TITLE
Discussion surrounding committing one off scripts into the repo

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#969]
### Descriptive summary

I voiced some concern this morning regarding checking in one off scripts into the repo. These one off scripts are usually used for something like metadata remediation or something of the sort. Once these scripts start making it into the repo, they continue to flood in. 

The argument for keeping these around is "what if someone needs that script" or "what if someone forgets what they did". However, I feel that is idealistic in the approach. Chances are that someone will just write their own one off script or not take the time to update theirs IF it needs to be used again.

If there is a script that is going to be a one off sort of thing that gets checked into the repo should in my opinion be removed as part of the ticket. 

These scripts can be kept locally if someone wants to keep it around or there will be history in the revision control on github. I was thinking the process could look something like:

IF someone wants to check in a one off script to the project these things should happen:
  It should be tested
  It gets checked in and merged
  It gets tested on the staging site
  It gets QAed
  Before the ticket is closed and QA is up it gets removed in a new PR

@wickr @jechols We wanted to see where you stood on this and we can make a decision at quarterly.

**Comment by jechols** [comment]
I'm not sure there's a blanket one-size-fits-all approach to handle "one-off" scripts.  If a dev has a useful one-off, I think they have to make a case to include it, not just check it in.  Otherwise we're doing all those extra steps (unit testing, review, testing on staging, QA, and a final removal) a lot and for very little gain.

I made a PR a while ago with a seed data loader, and my approach was basically "is this useful to anybody else?"  The answer was "not really", so it's not a part of the repo or the github history, and that's a good thing in my opinion.  Adding a bunch of overhead to get that in the repo would have been a waste of time if nobody else cared to use it.  I still maintain the script locally because it's useful to *me*, but as long as it's just me, I definitely can't justify the time it would take to incorporate it, even temporarily.

**Comment by straleyb** [comment]
Im actually fine with that as well. I think its good to make sure to keep that stuff out of the repo. I wanted to make sure and provide an outlet just in case. But I think your idea of making a good argument for why it should end up in the repo is a good ruleset. If you can determine why this script would be good to keep around in the long run, then we can integrate it. If you cant think of a good reason to really check it in, then lets just forego it.

**Comment by straleyb** [comment]
Im going to close this now since we'll be talking about it. An ADR should be written up for it.
