### ISSUE TITLE
"Random" FileSet being attached to work when work is added to a collection

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#970]
### Descriptive summary

This issue is when a user ingests a work with a file attached and adds it to a collection. The work then gets another fileset within the collection appended or attached to it as well. When you view this works show page you can see the other fileset along with the one that was originally added to the work.

This can be recreated by ingesting a new work on staging and adding it to the OSU test 002 collection.
When the work saves and the files process, the fileset gets appended.

### Expected behavior

When a work is created and added to a collection, a random fileset does not get attached.

**Comment by shieldsb** [comment]
https://staging.oregondigital.org/concern/images/gq67jr188?locale=en#?c=0&m=0&s=0&cv=0&xywh=-2045%2C-128%2C6188%2C2833
https://staging.oregondigital.org/concern/images/k0698755v?locale=en#?c=0&m=0&s=0&cv=0&xywh=-3018%2C-195%2C8513%2C3897
![works list view](https://user-images.githubusercontent.com/53542788/73682647-a3b6b700-4675-11ea-9420-0d15b65e677c.jpg)
![work review page results](https://user-images.githubusercontent.com/53542788/73682660-a87b6b00-4675-11ea-9a70-0eaaeb0b0bb6.jpg)
![work review page results2](https://user-images.githubusercontent.com/53542788/73682663-ab765b80-4675-11ea-8d8b-dae807815161.jpg)

**Comment by shieldsb** [comment]
tested again today 2/3/20, the image did not appear as the correct thumbnail in the works list, but the image still appeared at the end of the pdf/work it attached to.  I did a second test into a different collection with the same result.  Also, while doing QA for the new cluster, I performed the same test into the same collection with no issues/expected behavior, so this is a staging issue. 

https://staging.oregondigital.org/concern/images/gt54kn088?locale=en#?c=0&m=0&s=0&cv=0&xywh=-4539%2C-284%2C12376%2C5666

![image](https://user-images.githubusercontent.com/53542788/73700260-ea6ad800-469a-11ea-9fbe-77831a5d4e7d.png)

**Comment by jechols** [comment]
Thinking of the problems with bad indexing, I wonder if the weird out-of-sync issues we've seen could be a contributing factor.  @straleyb is this reproducible in dev at all, or *just* the old staging?

**Comment by straleyb** [comment]
@jechols Just the old staging from what Ive been able to gather, but I haven't quite done extensive testing, so im not 100% sure.

**Comment by jechols** [comment]
Well, that does suggest busted old data is getting associated with things.  Given how Fedora stores things like containers separately from what's *in* a container, and everything is referenced by ids, I bet there are bits of old data that never got reindexed after our Solr bombing, and are now getting associated with the wrong data.

On the plus side this is probably a one-off.  On the minus side, we are going to have a rough time if we can't be 100% certain our index is always a perfect reflection of our Fedora data.
